/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

#import "VMUAddressRange.h"
#import "Symbolication-Structs.h"
#import <Foundation/NSObject.h>
#import "NSCoding.h"


@interface VMUAddressRange : NSObject <NSCoding> {
	VMURange _addressRange;
}
// in a protocol: -(nullable instancetype)initWithCoder:(NSCoder *)coder;
// in a protocol: -(void)encodeWithCoder:(id)coder;
@end

@interface VMUAddressRange (Private)
-(void)setAddressRange:(VMURange)range;
@end

