/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

#import "Symbolication-Structs.h"
#import "NSCoding.h"
#import <Foundation/NSObject.h>
#import "NSCopying.h"
#include <mach/machine.h>


@interface VMUArchitecture : NSObject <NSCoding, NSCopying> {
	cpu_type_t _cpuType;
	cpu_subtype_t _cpuSubtype;
}
// inherited: +(void)initialize;
+(VMUArchitecture*)currentArchitecture;
+(VMUArchitecture*)anyArchitecture;
+(VMUArchitecture*)ppcArchitecture;
+(VMUArchitecture*)ppc32Architecture;
+(VMUArchitecture*)ppc64Architecture;
+(VMUArchitecture*)i386Architecture;
+(VMUArchitecture*)x86_32Architecture;
+(VMUArchitecture*)x86_64Architecture;
+(VMUArchitecture*)architectureWithCpuType:(cpu_type_t)cpuType cpuSubtype:(cpu_subtype_t)subtype;
-(id)initWithCpuType:(cpu_type_t)cpuType cpuSubtype:(cpu_subtype_t)subtype;
// in a protocol: -(id)initWithCoder:(id)coder;
// in a protocol: -(void)encodeWithCoder:(id)coder;
// in a protocol: -(id)copyWithZone:(NSZone*)zone;
-(BOOL)isBigEndian;
-(BOOL)isLittleEndian;
-(BOOL)is32Bit;
-(BOOL)is64Bit;
-(BOOL)isEqualToArchitecture:(VMUArchitecture*)architecture;
// inherited: -(BOOL)isEqual:(id)equal;
// inherited: -(unsigned)hash;
-(BOOL)matchesArchitecture:(VMUArchitecture*)architecture;
-(cpu_type_t)cpuType;
-(cpu_subtype_t)cpuSubtype;
// inherited: -(id)description;
@end

@interface VMUArchitecture (Private)
-(VMURange)commpageAddressRange;
-(VMURange)objcpageAddressRange;
@end

