/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

#import "VMUSymbolExtractor.h"

@class VMUMachOHeader;


@interface VMUDebugMapExtractor : VMUSymbolExtractor {
}
+(VMUDebugMapExtractor*)debugMapExtractorWithMachOHeader:(VMUMachOHeader*)machOHeader;
-(id)initWithMachOHeader:(id)machOHeader;
-(void)readDebugMapsFromMachOHeader:(id)machOHeader nsyms:(unsigned)nsyms nlist:(id)nlist stringTable:(id)table;
-(void)readDSymFileForHeader:(id)header;
@end

