/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

#import "Symbolication-Structs.h"
#import "VMUMemory_Base.h"
#import "VMUMemory.h"

@class VMUMachTaskContainer, VMUArchitecture;

@interface VMUMemory_NonContiguousTask : VMUMemory_Base <VMUMemory> {
	VMUMachTaskContainer* _machTaskContainer;
	VMURange _addressRange;
	VMUArchitecture* _architecture;
}
+(id)memoryWithPid:(int)pid;
+(id)memoryWithPid:(int)pid addressRange:(VMURange)range architecture:(id)architecture;
+(id)memoryWithMachTaskContainer:(id)machTaskContainer;
+(id)memoryWithMachTaskContainer:(id)machTaskContainer addressRange:(VMURange)range architecture:(id)architecture;
-(id)initWithMachTaskContainer:(id)machTaskContainer addressRange:(VMURange)range architecture:(id)architecture;
-(id)machTaskContainer;
-(VMURange)regionAtAddress:(unsigned long long)address minProtection:(int)protection;
// in a protocol: -(VMURange)addressRange;
// in a protocol: -(id)architecture;
// in a protocol: -(BOOL)isContiguous;
// in a protocol: -(id)memoryAtAddress:(unsigned long long)address maxSize:(unsigned long long)size;
// in a protocol: -(id)memoryFromSubRange:(VMURange)subRange mapToAddress:(unsigned long long)address architecture:(id)architecture;
// in a protocol: -(id)view;
// in a protocol: -(id)swappedView;
// in a protocol: -(id)description;
// inherited: -(void)dealloc;
@end

