/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

#import "Symbolication-Structs.h"
#import "VMUMemory_Base.h"
#import "VMUMemory.h"

@class NSDate, VMUArchitecture, NSString, NSMutableDictionary;

@interface VMUMemory_File : VMUMemory_Base <VMUMemory> {
	char* _mappedAddress;
	unsigned _mappedSize;
	NSDate* _lastModifiedTimestamp;
	VMURange _addressRange;
	VMURange _fileRange;
	NSString* _path;
	VMUArchitecture* _architecture;
	NSMutableDictionary* _sharedCacheMap;
}
+(VMUMachOHeader*)headerWithPath:(NSString*)path;
+(VMUMachOHeader*)headerFromSharedCacheWithPath:(NSString*)path;
+(id<VMUMemory>)memoryWithPath:(NSString*)path;
+(id<VMUMemory>)memoryWithPath:(NSString*)path fileRange:(VMURange)range mapToAddress:(unsigned long long)address architecture:(VMUArchitecture*)architecture;
-(id)initWithPath:(id)path fileRange:(VMURange)range mapToAddress:(unsigned long long)address architecture:(id)architecture;
-(NSString*)path;
-(NSDate*)lastModifiedTimestamp;
-(void)buildSharedCacheMap;
-(unsigned long long)sharedCacheHeaderOffsetForPath:(NSString*)path;
-(BOOL)map;
// in a protocol: -(id)description;
// inherited: -(void)dealloc;
// inherited: -(void)finalize;
// in a protocol: -(VMURange)addressRange;
// in a protocol: -(id)architecture;
// in a protocol: -(BOOL)isContiguous;
// in a protocol: -(id)memoryAtAddress:(unsigned long long)address maxSize:(unsigned long long)size;
// in a protocol: -(id)memoryFromSubRange:(VMURange)subRange mapToAddress:(unsigned long long)address architecture:(id)architecture;
// in a protocol: -(id)view;
// in a protocol: -(id)swappedView;
@end
