/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DAVKit.framework/DAVKit
 */

#import "DAVKit-Structs.h"
#import <Foundation/NSObject.h>
#import "DAVAuthStore.h"

@class DAVChallenge, NSString;

@interface _DAVNaiveAuthStore : NSObject <DAVAuthStore> {
	NSString* baseHost;
	NSString* baseScheme;
	int basePort;
	DAVChallenge* authChallenge;
}
// inherited: -(id)init;
// inherited: -(void)dealloc;
// in a protocol: -(BOOL)hasCredentialsForSession:(id)session;
// in a protocol: -(BOOL)session:(id)session addAuthHeaderToMessage:(CFHTTPMessageRef)message;
// in a protocol: -(void)session:(id)session storeAuthChallenge:(id)challenge forURL:(id)url;
// in a protocol: -(void)clearAuthChallengeForSession:(id)session;
@end

