/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DAVKit.framework/DAVKit
 */

#import <Foundation/NSObject.h>
#import "DAVKit-Structs.h"
#import "AYAddress.h"
#import "NSCopying.h"


@interface AYAddress : NSObject <NSCopying> {
}
// inherited: +(void)initialize;
// inherited: +(id)allocWithZone:(NSZone*)zone;
+(id)_createAddressFromSockaddrBuffer:(struct sockaddr*)sockaddrBuffer;
+(id)addressWithData:(id)data;
+(id)addressWithString:(id)string;
+(id)addressOfPeerFromSocket:(int)socket;
+(id)addressOfLocalFromSocket:(int)socket;
+(id)addressesFromDataAddresses:(id)dataAddresses;
+(id)IPV4AddressesFromDataAddresses:(id)dataAddresses;
-(id)initAddressWithData:(id)data;
-(id)initAddressWithString:(id)string;
-(id)initAddressWithPeerFromSocket:(int)socket;
-(id)initAddressWithLocalFromSocket:(int)socket;
-(id)type;
-(id)addressAsString;
-(int)port;
-(BOOL)isLocalAddressConnectingTo:(id)to;
-(id)addressAsData;
-(void)getAddressAsSockAddr:(struct sockaddr*)addr length:(int*)length;
// inherited: -(id)description;
-(id)URLToAddressWithScheme:(id)scheme;
-(id)URLToAddressWithScheme:(id)scheme andPort:(int)port;
-(id)URLToAddressWithScheme:(id)scheme andPort:(int)port URI:(id)uri;
// in a protocol: -(id)copyWithZone:(NSZone*)zone;
-(void)dumpInternal;
@end

@interface AYAddress (LocalProtection)
+(void)startListeningToNetworkConfiguration;
+(void)updateNetmasksFromStoreWithChangedKeys:(id)changedKeys;
+(void)stopListeningToNetworkConfiguration;
+(unsigned)netMaskForIPV4Address:(id)ipv4Address;
@end

