/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DAVKit.framework/DAVKit
 */

#import "DAVKit-Structs.h"
#import "AYOperation.h"

@class NSData, NSArray;

@interface AYHost : AYOperation {
	CFHostRef _hostRef;
	CFHostClientContext _context;
	NSArray* _names;
	NSArray* _addresses;
	NSData* _isReachable;
	BOOL _wasCreatedFromName;
	id _origin;
	int _infoType;
}
+(id)hostWithName:(id)name;
+(id)hostWithAddress:(id)address;
-(void)_setClient;
-(id)initHostWithName:(id)name;
-(id)initHostWithAddress:(id)address;
// inherited: -(void)dealloc;
// inherited: -(void)finalize;
-(void)_launchInfoResolutionWithType:(int)type;
-(void)resolveAddresses;
-(id)addresses;
-(void)resolveNames;
-(id)names;
-(void)checkReachability;
-(unsigned)reachability;
// inherited: -(void)endOperationWithError:(id)error;
-(void)_handleInfoResolutionEventWithType:(int)type error:(const XXStruct_K5nmsA*)error;
// inherited: -(id)description;
@end

