/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DAVKit.framework/DAVKit
 */

#import <Foundation/NSObject.h>
#import "DAVKit-Structs.h"

@class NSString;

@interface DAVCertificateInfo : NSObject {
	NSString* _title;
	NSString* _message;
	SecTrust* _trustRef;
	int _returnCode;
}
-(id)initWithTitle:(id)title message:(id)message trustRef:(SecTrust*)ref;
// inherited: -(void)dealloc;
-(void)setReturnCode:(int)code;
-(int)returnCode;
-(id)title;
-(id)message;
-(SecTrust*)trustRef;
@end

