/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DAVKit.framework/DAVKit
 */

#import "DAVRequest.h"


@interface DAVGetToFile : DAVRequest {
}
+(id)getRequestWithURL:(id)url toFileHandle:(id)fileHandle;
+(id)getRequestWithSession:(id)session path:(id)path toFileHandle:(id)fileHandle;
+(id)getRequestWithSession:(id)session URI:(id)uri toFileHandle:(id)fileHandle;
-(id)initGetWithURL:(id)url toFileHandle:(id)fileHandle;
-(id)initGetWithSession:(id)session path:(id)path toFileHandle:(id)fileHandle;
-(id)initGetWithSession:(id)session URI:(id)uri toFileHandle:(id)fileHandle;
@end

