/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DAVKit.framework/DAVKit
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface DAVXMLNSBag : NSObject {
	NSMutableDictionary* tagMapping;
	NSMutableDictionary* allNS;
	unsigned nsCounter;
	void* reserved1;
}
// inherited: +(void)initialize;
+(id)_smartTagForTag:(id)tag;
+(id)namespaceForTag:(id)tag;
+(void)registerNSTags:(id)tags withNamespace:(id)aNamespace;
// inherited: -(id)init;
// inherited: -(void)dealloc;
-(id)tagForNSTag:(id)nstag;
-(id)allXMLNSAttributes;
@end

