/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DAVKit.framework/DAVKit
 */

#import <Foundation/NSString.h>


@interface NSString (DAVAdditions)
+(unsigned)encodingForIANACharSetName:(id)ianacharSetName;
+(id)IANACharSetNameFromEncoding:(unsigned)encoding;
-(id)stringByXMLQuoting;
-(id)stringByURLQuotingPaths;
-(id)stringByURLQuoting;
-(id)stringByURLUnquoting;
-(id)mimeAnalysis;
@end

