/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DAVKit.framework/DAVKit
 */

#import <Foundation/NSURL.h>


@interface NSURL (DAVAdditions)
+(int)classicPortForScheme:(id)scheme;
+(id)URLWithDirtyString:(id)dirtyString;
+(id)URLWithScheme:(id)scheme host:(id)host port:(int)port uri:(id)uri;
-(id)initWithDirtyString:(id)dirtyString;
-(id)uri;
-(id)URLWithUsername:(id)username;
-(id)URLWithoutUsername;
-(id)URLWithoutPassword;
-(id)initWithScheme:(id)scheme host:(id)host port:(int)port uri:(id)uri;
@end

