/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import <QuartzCore/CALayer.h>
#import "CAPropertyInfo.h"
#import "CAMediaTiming2.h"
#import "QuartzCore-Structs.h"
#import <Foundation/NSObject.h>

@class NSArray, NSString, NSDictionary;

@interface CALayer ()
// inherited: -(id)retain;
-(void)release;
// inherited: -(unsigned)retainCount;
// inherited: -(id)init;
-(id)initWithBounds:(CGRect)bounds;
// inherited: -(void)dealloc;
// inherited: -(id)debugDescription;
-(id)valueForKey:(id)key;
-(id)valueForUndefinedKey:(id)undefinedKey;
-(void)setValue:(id)value forKey:(id)key;
-(void)setValue:(id)value forUndefinedKey:(id)undefinedKey;
-(id)valueForKeyPath:(id)keyPath;
-(void)setValue:(id)value forKeyPath:(id)keyPath;
-(BOOL)_scheduleAnimationTimer;
-(void)_cancelAnimationTimer;
-(void)setNeedsDisplay;
-(void)setNeedsDisplayInRect:(CGRect)rect;
-(void)_display;
-(void)setNeedsLayout;
-(void)layoutIfNeeded;
@end

@interface CALayer (CALayerScrolling_private)
-(void)_scrollPoint:(CGPoint)point fromLayer:(id)layer;
-(void)_scrollRect:(CGRect)rect fromLayer:(id)layer;
-(CGRect)_visibleRectOfLayer:(id)layer;
@end

@interface CALayer (CALayerPrivate) <CAPropertyInfo>
@property(assign) BOOL sortsSublayers;
@property(assign) float rasterizationScale;
@property(assign, getter=isRasterizationEnabled) BOOL rasterizationEnabled;
@property(assign) CGAffineTransform contentsTransform;
@property(assign) BOOL clearsContext;
@property(assign) BOOL canDrawConcurrently;
@property(assign) BOOL needsLayoutOnGeometryChange;
// in a protocol: +(id)properties;
+(/*function-pointer*/ void*)CA_setterForType:(int)type;
+(/*function-pointer*/ void*)CA_getterForType:(int)type;
// inherited: +(BOOL)resolveInstanceMethod:(SEL)method;
-(void)reloadValueForKeyPath:(id)keyPath;
-(BOOL)_canDisplayConcurrently;
-(BOOL)drawsMipmapLevels;
-(BOOL)hasBeenCommitted;
-(void)invalidateContents;
-(void)setContentsChanged;
-(void*)regionBeingDrawn;
-(void)_prepareContext:(CGContextRef)context;
-(BOOL)layoutIsActive;
-(void)layoutBelowIfNeeded;
-(BOOL)ignoresHitTesting;
-(BOOL)isDescendantOf:(id)of;
-(id)ancestorSharedWithLayer:(id)layer;
-(CGSize)size;
-(id)layerBeingDrawn;
-(id)layerAtTime:(double)time;
-(Layer*)_copyRenderLayer:(Transaction*)layer flags:(unsigned*)flags;
-(bool)_renderLayerDefinesProperty:(unsigned)property;
-(unsigned)_renderLayerPropertyAnimationFlags:(unsigned)flags;
-(void)layerDidBecomeVisible:(BOOL)layer;
-(BOOL)isFlipped;
-(void)setFlipped:(BOOL)flipped;
@end

