/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import <Foundation/NSObject.h>
#import "QuartzCore-Structs.h"


__attribute__((visibility("hidden")))
@interface CARenderObject : NSObject {
@private
	Object* _object;
}
+(id)objectWithRenderObject:(Object*)renderObject;
-(id)initWithRenderObject:(Object*)renderObject;
-(Object*)object;
-(Object*)CA_copyRenderValue;
// inherited: -(void)dealloc;
@end

