/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MIME.framework/MIME
 */

#import "MessageBody.h"

@class MimePart;

@interface MimeBody : MessageBody {
	MimePart* _topLevelPart;
	unsigned _preferredTextEncoding;
	unsigned _preferredAlternative : 16;
	unsigned _numAlternatives : 16;
}
// inherited: +(void)initialize;
+(id)versionString;
+(id)copyNewMimeBoundary;
// inherited: -(id)init;
// inherited: -(void)dealloc;
-(id)topLevelPart;
-(void)setTopLevelPart:(id)part;
-(unsigned long)preferredTextEncoding;
-(void)setPreferredTextEncoding:(unsigned long)encoding;
-(id)mimeType;
-(id)mimeSubtype;
-(id)partWithNumber:(id)number;
-(void)decodeIfNecessary;
// inherited: -(unsigned)numberOfAttachmentsSigned:(BOOL*)attachmentsSigned encrypted:(BOOL*)encrypted;
// inherited: -(id)attachments;
// inherited: -(BOOL)isHTML;
// inherited: -(BOOL)isRich;
// inherited: -(id)contentToOffset:(unsigned)offset resultOffset:(unsigned*)offset2 asHTML:(BOOL)html isComplete:(BOOL*)complete;
-(unsigned)totalTextSize;
-(int)numberOfAlternatives;
-(void)setPreferredAlternative:(int)alternative;
-(int)preferredAlternative;
-(id)preferredBodyPart;
// inherited: -(id)textHtmlPart;
@end

