/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MIME.framework/MIME
 */

#import <Foundation/NSScanner.h>
#import "MIME-Structs.h"


@interface NSScanner (NSScannerUtils)
-(id)mf_nextTokenWithPunctuation:(CFCharacterSetRef)punctuation;
-(BOOL)mf_scanUpAndOverString:(id)string;
@end

