/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MIME.framework/MIME
 */

#import "WRObject.h"
#import "MIME-Structs.h"
#import "WeakReferenceHolder.h"


@interface WeakSet : WRObject <WeakReferenceHolder> {
@private
	CFSetRef _set;
}
// inherited: -(id)init;
// in a protocol: -(void)dealloc;
// in a protocol: -(void)objectWillBeDeallocated:(id)object;
-(void)addObject:(id)object;
-(void)removeObject:(id)object;
-(void)applyFunction:(/*function-pointer*/ void*)function context:(void*)context;
@end

