/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

#import "ML3Collection.h"


@interface ML3Genre : ML3Collection {
}
+(void)initialize;
+(id)databaseTable;
+(id)defaultOrderingProperties;
+(id)joinClauseForProperty:(id)property;
+(id)orderingCollationForProperty:(id)property;
+(id)sectionPropertyForProperty:(id)property;
@end

