/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

#import <Foundation/NSObject.h>

@class NSLock, CPLRUDictionary, NSString;

@interface ML3StringTransformer : NSObject {
@private
	NSString* _nameTransform;
	CPLRUDictionary* _transformCache;
	NSLock* _transformCacheLock;
}
@property(retain, nonatomic) NSString* nameTransform;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)flushTransformCache;
-(void)resizeTransformCacheToDefaultSize;
-(void)resizeTransformCacheToMaxSize:(unsigned)maxSize;
-(const unsigned short*)transformedCharactersForCharacters:(const unsigned short*)characters length:(unsigned*)length;
@end

