/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

#import "MLSectionData.h"


__attribute__((visibility("hidden")))
@interface MLMutableSectionData : MLSectionData {
}
-(id)init;
-(void)appendTitle:(id)title sectionLength:(unsigned)length;
@end

