/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

#import "MLPhotoDCFObject.h"
#import "MusicLibrary-Structs.h"

@class NSDate, NSMutableSet, NSString, MLPhotoDCFDirectory;

@interface MLPhotoDCFFileGroup : MLPhotoDCFObject {
@private
	id _delegate;
	MLPhotoDCFDirectory* _directory;
	NSString* _directoryPath;
	NSString* _prebakedThumbnailPath;
	NSString* _videoFileExtension;
	NSMutableSet* _extensions;
	NSDate* _date;
	NSString* _preferredExtension;
	unsigned _hash;
	unsigned _hashComputed : 1;
	unsigned _addedExtensions : 1;
	unsigned _writeIsPending : 1;
}
+(CGImageRef)createThumbnailOfImage:(CGImageRef)image format:(int)format fullPath:(id)path orientation:(int)orientation outThumbnailData:(id*)data;
-(id)initWithName:(id)name number:(int)number directory:(id)directory;
-(void)dealloc;
-(void)setDelegate:(id)delegate;
-(id)delegate;
-(id)directory;
-(id)imageSourceTypeHint;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(BOOL)isValid;
-(BOOL)isValidImage;
-(void)addExtension:(id)extension;
-(id)date;
-(void)setDate:(id)date;
-(int)compare:(id)compare;
-(id)description;
-(void)addExtensionsFromMetadataDirectory;
-(void)forceAddExtensionsFromMetadataDirectory;
-(id)extensions;
-(id)pathForGroupWithoutExtension;
-(id)pathForMetadata;
-(id)pathForMetadataWithGroupName;
-(void)createMetadataDirectoryIfNecessary;
-(id)pathForFullSizeImage;
-(id)pathForVideoFile;
-(id)pathForTrimmedVideoFile;
-(id)thumbnailFilename;
-(id)prebakedThumbnailFilename;
-(id)prebakedLandscapeScrubberThumbnailsFilename;
-(id)prebakedPortraitScrubberThumbnailsFilename;
-(id)prebakedWildcatThumbnailsFilename;
-(id)lowResolutionFilename;
-(id)videoPreviewFilename;
-(id)pathForThumbnailFile;
-(id)pathForPrebakedThumbnail;
-(id)pathForPrebakedLandscapeScrubberThumbnails;
-(id)pathForPrebakedPortraitScrubberThumbnails;
-(id)pathForPrebakedWildcatThumbnailsFile;
-(id)pathForLowResolutionFile;
-(id)pathForVideoPreviewFile;
-(BOOL)hasThumbnail;
-(BOOL)hasVideoFile;
-(BOOL)hasPrebakedThumbnail;
-(BOOL)hasPrebakedLandscapeScrubberThumbnails;
-(BOOL)hasPrebakedPortraitScrubberThumbnails;
-(BOOL)hasPrebakedWildcatThumbnails;
-(void)deleteFiles;
-(void)setWriteIsPending:(BOOL)pending;
-(BOOL)isWritePending;
-(void)createWildcatThumbnailsFromImage:(CGImageRef)image orientation:(int)orientation options:(id)options delegate:(id)delegate;
@end

