/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

#import <Foundation/NSObject.h>
#import "MusicLibrary-Structs.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface MLSQLResultFilter : NSObject {
@private
	NSNumber* _countLimit;
	NSNumber* _sumLimitValue;
	NSString* _sumLimitColumnName;
}
@property(copy, nonatomic) NSNumber* countLimit;
@property(copy, nonatomic) NSNumber* sumLimitValue;
@property(copy, nonatomic) NSString* sumLimitColumnName;
-(void)dealloc;
-(CPRecordIDArrayRef)copyFilteredRecordIDArray:(CPRecordIDArrayRef)array limitValueArray:(CFArrayRef)array2;
@end

