/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

#import "MLSQLCode.h"


__attribute__((visibility("hidden")))
@interface MLSQLGroupBy : MLSQLCode {
}
+(id)expressionToken;
-(id)initWithGroupColumnsString:(id)groupColumnsString;
-(id)groupColumnsString;
-(void)dealloc;
@end

