/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */


#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <GraphicsServices/GSEvent.h>
#import <UIKit/UIKit-Structs.h>

typedef struct __CKSMSRecord* CKSMSRecordRef;

typedef struct {
	int _field1;
	int _field2;
} XXStruct_K5nmsA;

typedef struct __CKSMSAddress* CKSMSAddressRef;

typedef struct CGImageSource* CGImageSourceRef;


