/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class CKService, NSMutableDictionary, NSString, NSMutableArray, NSArray, CKMessageComposition, CKMessage;

@interface CKConversation : NSObject {
	NSMutableArray* _messages;
	NSString* _name;
	int _unreadCount;
	NSMutableArray* _failedMessages;
	NSMutableArray* _pendingMessages;
	CKMessage* _latestIncomingMessage;
	BOOL _hasPlaceholder;
	CKMessage* _placeholderMessage;
	NSArray* _names;
	NSArray* _recipients;
	int _groupID;
	NSMutableDictionary* _groupMessages;
	NSMutableArray* _queuedGroupMessages;
	int _groupAddStack;
	BOOL _moreMessagesToLoad;
	int _limitToLoad;
	CKService* _service;
	BOOL _updatesDisabled;
}
@property(readonly, assign, nonatomic) CKService* service;
@property(assign, nonatomic) BOOL updatesDisabled;
@property(readonly, assign, nonatomic) NSMutableArray* failedMessages;
@property(retain, nonatomic) CKMessageComposition* unsentComposition;
-(int)groupID;
-(id)initWithGroupID:(int)groupID service:(id)service;
-(id)recipient;
-(void)dealloc;
-(void)setName:(id)name;
-(id)name;
-(id)latestMessage;
-(id)date;
-(void)setRecipients:(id)recipients;
-(id)recipients;
-(void)_recalculateUnreadCounts;
-(void)removeMessage:(id)message;
-(BOOL)isEmpty;
-(BOOL)isPlaceholder;
-(id)placeholderMessage;
-(void)_setPlaceholderMessage:(id)message;
-(void)updateMessage:(id)message;
-(int)addMessage:(id)message incrementUnreadCount:(BOOL)count;
-(void)_beginGroupAdd;
-(void)_addGroupMessage:(id)message;
-(int)_endGroupAdd:(BOOL)add;
-(void)resetPendingMessages;
-(void)markAllMessagesAsRead;
-(void)removeAllMessages;
-(void)_deleteAllMessagesAndRemoveGroup:(BOOL)group;
-(void)deleteAllMessages;
-(void)deleteAllMessagesAndRemoveGroup;
-(BOOL)moreMessagesToLoad;
-(void)_postUpdate;
-(void)_reloadMessagesToLimit;
-(void)loadAllMessages;
-(void)loadMoreMessages;
-(id)pendingMessages;
-(id)messages;
-(id)latestIncomingMessage;
-(void)setUnreadCount:(int)count;
-(int)unreadCount;
-(BOOL)hasUnreadMessages;
-(id)_trulyLatestMessage;
-(int)compareByDateDescending:(id)descending;
-(void*)abRecord;
-(int)propertyType;
-(int)identifier;
-(void)resetCaches;
-(id)groupMessageWithAssociationID:(int)associationID;
-(void)pendingMessagesTotalMessages:(int*)messages percentComplete:(float*)complete;
@end

