/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "ChatKit-Structs.h"
#import "CKCompressibleImageMediaObject.h"


@interface CKFixedImageMediaObject : CKCompressibleImageMediaObject {
}
+(id)mimeTypesToFileExtensions;
-(BOOL)shouldTranscodeForMMS;
@end

