/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "CKService.h"

@class NSMutableArray;

@interface CKLoopbackService : CKService {
	NSMutableArray* _conversations;
}
+(id)sharedLoopbackService;
-(id)newMessageWithComposition:(id)composition forConversation:(id)conversation;
-(id)placeholderMessageForConversation:(id)conversation withDate:(id)date;
-(void)addMessageToStore:(id)store incrementUnreadCount:(BOOL)count;
-(void)sendMessage:(id)message;
-(void)_reallySendMessage:(id)message;
-(void)_receiveMessageForMessage:(id)message;
-(int)unreadConversationCount;
-(int)unreadCount;
-(int)unreadCountForConversation:(id)conversation;
-(id)lookupRecipientsForConversation:(id)conversation;
-(void)fixupNames;
-(id)conversationSummaries:(id*)summaries groupIDs:(id*)ids;
-(id)messagesForConversation:(id)conversation limit:(int)limit moreToLoad:(BOOL*)load;
-(int)createConversationWithRecipients:(id)recipients;
-(BOOL)dbFull;
-(void)dealloc;
@end

