/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class CKConversationList, NSString, CKEntity;

@interface CKService : NSObject {
	NSString* _serviceID;
	CKConversationList* _conversationList;
}
@property(readonly, assign, nonatomic) NSString* serviceID;
@property(readonly, assign, nonatomic) CKConversationList* conversationList;
-(id)initWithServiceID:(id)serviceID;
-(int)createConversationWithRecipients:(id)recipients;
-(int)conversationIDWithRecipients:(id)recipients;
-(int)unreadConversationCount;
-(int)unreadCountForConversation:(id)conversation;
-(id)headerTitleForEntities:(id)entities;
-(id)headerTitleForComposeRecipients:(id)composeRecipients mediaObjects:(id)objects subject:(id)subject;
-(BOOL)canSendToRecipients:(id)recipients withAttachments:(id)attachments alertIfUnable:(BOOL)unable;
-(void)markAllMessagesInConversationAsRead:(id)conversationAsRead;
-(BOOL)dbFull;
-(BOOL)canSendMessageWithMediaObjectTypes:(int*)mediaObjectTypes;
-(void)dealloc;
-(id)placeholderMessageForConversation:(id)conversation withDate:(id)date;
-(id)newMessageWithComposition:(id)composition forConversation:(id)conversation;
-(id)newMessageWithMessage:(id)message forConversation:(id)conversation isForward:(BOOL)forward;
-(void)sendMessage:(id)message;
-(id)conversationSummaries:(id*)summaries groupIDs:(id*)ids;
-(id)lookupRecipientsForConversation:(id)conversation;
-(void)fixupNames;
-(int)maxRecipientCount;
-(int)unreadCount;
-(id)messagesForConversation:(id)conversation limit:(int)limit moreToLoad:(BOOL*)load;
-(BOOL)restrictsMediaObjects;
-(BOOL)canAcceptMediaObject:(id)object givenMediaObjects:(id)objects;
-(BOOL)canAcceptMediaObjectType:(int)type givenMediaObjects:(id)objects;
-(double)maxTrimDurationForMediaType:(int)mediaType;
-(CKEntity*)copyEntityForAddressString:(NSString*)addressString;
-(id)unknownEntity;
-(id)abPropertyTypes;
-(BOOL)isValidAddress:(id)address;
-(int)maxAttachmentCount;
-(void)deleteMessagesForConversationIDs:(id)conversationIDs removeConversations:(BOOL)conversations;
@end

