/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "ChatKit-Structs.h"
#import "CKBalloonView.h"

@class NSString;

@interface CKSimpleBalloonView : CKBalloonView {
	NSString* _text;
}
+(float)minimumBubbleHeight;
+(float)heightForText:(id)text width:(float)width includeBuffers:(BOOL)buffers;
+(BOOL)showsSubject;
-(id)text;
-(id)subject;
-(void)setText:(id)text;
-(void)setMessagePart:(id)part;
-(void)setComposition:(id)composition;
-(void)prepareForReuse;
-(void)dealloc;
-(void)setBackgroundColor:(id)color;
-(CGRect)subjectBounds;
-(CGRect)textBounds;
-(void)drawRect:(CGRect)rect;
@end

