/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "ChatKit-Structs.h"
#import <UIKit/UILabel.h>


@interface CKSummaryLabel : UILabel {
	BOOL _hasEmoji;
}
-(void)setText:(id)text;
-(void)drawRect:(CGRect)rect;
@end

