/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "ChatKit-Structs.h"
#import "CKMediaObject.h"


@interface CKVCardMediaObject : CKMediaObject {
}
+(id)mimeTypesToFileExtensions;
-(int)mediaType;
-(BOOL)shouldTranscodeForMMS;
-(Class)balloonPreviewClassWithPreviewData:(id)previewData;
-(void)configureBalloon:(id)balloon withPreviewData:(id)previewData;
@end

