/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "ChatKit-Structs.h"
#import <UIKit/UIControl.h>


@interface MailMultiSelectButton : UIControl {
	unsigned _isChecked : 1;
	unsigned _isSelected : 1;
}
+(float)defaultWidth;
+(id)minusImage;
+(id)plusImage;
+(id)minusCenterImage;
-(id)initWithRemoveControl:(id)removeControl checked:(BOOL)checked;
-(void)toggleRotate:(BOOL)rotate;
-(BOOL)isRotated;
-(BOOL)isRotating;
-(BOOL)isHiding;
-(void)setHiding:(BOOL)hiding;
-(void)drawRect:(CGRect)rect;
-(void)setChecked:(BOOL)checked selected:(BOOL)selected;
@end

