/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <Foundation/NSFileManager.h>


@interface NSFileManager (NSFileManagerAdditions_MobileSlideShow)
-(id)makeUniqueDirectoryWithPath:(id)path;
-(id)tmpFileForVideoTranscode;
@end

