/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PhotoLibrary-Structs.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import <UIKit/UIView.h>

@class PLImageCountCell, PLThumbnailTableCell, NSMutableArray, NSArray, UITableView, UIToolbar, MLPhotoAlbum, PLEmptyAlbumView;

@interface PLAlbumView : UIView <UITableViewDataSource, UITableViewDelegate> {
	MLPhotoAlbum* _album;
	int _filter;
	UITableView* _indexTableView;
	UIToolbar* _toolbar;
	unsigned _gridHeight;
	CGSize _cellSize;
	BOOL _showImageCount;
	id _delegate;
	PLThumbnailTableCell* _highlightedCell;
	PLImageCountCell* _imageCountCell;
	PLEmptyAlbumView* _emptyAlbumView;
	BOOL _forceTableReload;
	BOOL _pictureWasTakenSinceLastReload;
	BOOL _isCameraAlbum;
	BOOL _didScrollToBottom;
	UIEdgeInsets _lastTableContentInset;
	unsigned _multipleSelectionEnabled : 1;
	NSMutableArray* _selectedPhotos;
	CFDictionaryRef _selectedPhotoIndexesByRow;
	unsigned _canShowCopyCallout : 1;
}
@property(readonly, assign, nonatomic) NSArray* selectedPhotos;
@property(assign, nonatomic) BOOL multipleSelectionEnabled;
@property(assign, nonatomic) BOOL canShowCopyCallout;
@property(retain, nonatomic) UIToolbar* toolbar;
@property(assign, nonatomic) int filter;
@property(retain, nonatomic) MLPhotoAlbum* album;
@property(assign, nonatomic) id delegate;
// inherited: -(id)initWithFrame:(CGRect)frame;
// inherited: -(void)dealloc;
// in a protocol: -(int)tableView:(id)view numberOfRowsInSection:(int)section;
// in a protocol: -(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableCellSelectionStateDidChange:(id)tableCellSelectionState photo:(id)photo wasSelected:(BOOL)selected;
// in a protocol: -(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
// in a protocol: -(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)tableCellCopyCalloutWillDisappear:(id)tableCellCopyCallout;
-(void)tableCell:(id)cell requestsDeletionOfPhotoAtIndex:(unsigned)index;
-(void)storeCurrentConfiguration:(id)configuration;
-(void)loadCurrentConfiguration:(id)configuration;
-(void)setFrame:(CGRect)frame;
-(void)reloadIndexTable;
-(id)indexTable;
-(void)clearSelection;
-(void)scrollRowToVisible:(int)visible;
-(void)viewWillBeDisplayed;
-(id)indexTableView;
-(void)_scrollToBottom;
-(void)_setupIndexTable;
-(unsigned)_calculateGridHeightForAlbum:(id)album;
-(CGSize)_indexCellSizeForAlbum:(id)album;
-(id)_imageCountCell;
-(void)_albumContentsDidChange:(id)_albumContents;
-(void)_cameraAlbumDidChange:(id)_cameraAlbum;
-(void)_updateToolbar;
@end

