/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PLItem.h"


@interface PLAudio : PLItem {
}
// inherited: +(Class)_internalClass;
// inherited: -(id)initWithURL:(id)url;
// inherited: -(id)initWithData:(id)data;
// inherited: -(id)initWithData:(id)data pathExtension:(id)extension;
// inherited: -(void)dealloc;
// inherited: -(int)itemType;
-(void)setTitle:(id)title;
-(id)title;
// inherited: -(id)_MLPhoto;
// inherited: -(BOOL)_allowsRotation;
-(void)_applicationWillTerminate:(id)_application;
-(id)pathForVideoFile;
@end

