/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PhotoLibrary-Structs.h"
#import <UIKit/UIFrameAnimation.h>


@interface PLHopAnimation : UIFrameAnimation {
	CGPoint _startMid;
	CGPoint _endMid;
	CGPoint _control1;
	CGPoint _control2;
	float _aX;
	float _bX;
	float _cX;
	float _aY;
	float _bY;
	float _cY;
	double _cumulativeTime;
}
-(void)updateControlPoints;
// inherited: -(void)setStartFrame:(CGRect)frame;
// inherited: -(void)setEndFrame:(CGRect)frame;
// inherited: -(void)setProgress:(float)progress;
-(double)cumulativeTime;
@end

