/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <Availability2.h>

#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_3_2


#import "PhotoLibrary-Structs.h"
#import <UIKit/UITiledView.h>


@interface PLImageTileView : UITiledView {
	id _delegate;
	unsigned _notifyTapDelegate : 1;
}
// inherited: +(Class)tileClass;
+(int)tileWidth;
+(void)setTileSize:(CGSize)size;
-(id)initWithSize:(CGSize)size;
-(CGSize)imageSize;
-(void)setDelegate:(id)delegate;
// inherited: -(id)_createTileWithFrame:(CGRect)frame;
// inherited: -(CGRect)visibleRect;
// inherited: -(BOOL)tilesNeedDisplay;
// inherited: -(void)dealloc;
// inherited: -(void)touchesBegan:(id)began withEvent:(id)event;
// inherited: -(void)touchesMoved:(id)moved withEvent:(id)event;
// inherited: -(void)touchesEnded:(id)ended withEvent:(id)event;
// inherited: -(void)mouseDown:(GSEventRef)down;
// inherited: -(void)mouseUp:(GSEventRef)up;
// inherited: -(void)mouseDragged:(GSEventRef)dragged;
@end

#endif
