/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <MediaPlayer/UIMoviePlayerController.h>


@interface PLMoviePlayerController : UIMoviePlayerController {
	id _playerDelegate;
}
+(void)reset;
+(id)sharedMoviePlayerController;
// inherited: -(void)dealloc;
// inherited: -(void)setDelegate:(id)delegate;
// inherited: -(id)delegate;
@end

