/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <UIKit/UIView.h>
#import "PhotoLibrary-Structs.h"

@class UIImageView;

@interface PLSyncProgressView : UIView {
	UIImageView* _icon;
}
-(void)layoutSubviews;
// inherited: -(id)initWithFrame:(CGRect)frame;
// inherited: -(void)dealloc;
@end

