/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PLLibraryViewController.h"


@interface PLUILibraryViewController : PLLibraryViewController {
}
// inherited: -(void)dealloc;
// inherited: -(void)loadView;
// inherited: -(void)viewWillAppear:(BOOL)view;
-(void)cancelButtonClicked:(id)clicked;
// inherited: -(void)iTunesSyncDidFinish;
-(void)_setImagePickerMediaTypes:(id)types;
-(void)libraryView:(id)view didSelectAlbum:(id)album;
@end

