/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PhotoLibrary-Structs.h"
#import <Foundation/NSObject.h>

@class NSDictionary, PLCameraView, PLPhotoLibrary, UIWindow, PLCameraButtonBar, UITransitionView, NSString;

@interface PLUIController : NSObject {
	id _delegate;
	UIWindow* _window;
	struct {
		unsigned showingCamera : 1;
		unsigned allowsAlbumSelection : 1;
		unsigned allowsPlayingSlideshow : 1;
		unsigned allowsFullSizeImageDisplay : 1;
		unsigned displayingPhotoPicker : 1;
		unsigned allowsZoomingWhenCropping : 1;
		unsigned cropPhotoAfterSelection : 1;
		unsigned showCancelInNavBar : 1;
		unsigned showingCameraPreview : 1;
		unsigned hasStartedLocation : 1;
		unsigned wantsThrowViewOnSave : 1;
	} _flags;
	PLPhotoLibrary* _model;
	UITransitionView* _fullScreenTransitionView;
	PLCameraView* _cameraView;
	PLCameraButtonBar* _cameraRollButtonBar;
	int _barStyle;
	NSString* _cropTitle;
	NSString* _cropSubtitle;
	NSString* _cropButtonTitle;
	NSDictionary* _configuration;
}
+(id)sharedInstance;
+(BOOL)runningPhotosApplication;
// inherited: -(id)init;
// inherited: -(void)dealloc;
-(id)mainWindow;
-(void)setMainWindow:(id)window;
-(id)defaultPNGName;
-(void)setDelegate:(id)delegate;
-(id)contentViewWithFrame:(CGRect)frame;
-(void)setConfiguration:(id)configuration;
-(id)configuration;
-(int)barStyle;
-(void)setBarStyle:(int)style;
-(BOOL)allowsPlayingSlideshow;
-(void)setAllowsPlayingSlideshow:(BOOL)slideshow;
-(BOOL)allowsFullSizeImageDisplay;
-(void)setAllowsFullSizeImageDisplay:(BOOL)display;
-(void)_updateCameraViewGestures;
-(BOOL)allowsZoomingWhenCropping;
-(void)setAllowsZoomingWhenCropping:(BOOL)cropping;
-(int)allowedImageViewGestures;
-(BOOL)displayingPhotoPicker;
-(void)setDisplayingPhotoPicker:(BOOL)picker;
-(BOOL)wantsThrowViewOnSave;
-(void)_updateCameraPhotoSavingOptions;
-(void)setWantsThrowViewOnSave:(BOOL)save;
-(BOOL)cropPhotoAfterSelection;
-(void)_updateLocationRunState;
-(void)activeStateChanged:(id)changed;
-(void)setCropPhotoAfterSelection:(BOOL)selection;
-(id)cropTitle;
-(id)cropSubtitle;
-(id)cropButtonTitle;
-(void)setCropTitle:(id)title subtitle:(id)subtitle cropButtonTitle:(id)title3;
-(void)photoWasCroppedToRect:(CGRect)rect fullSizeImageData:(id)data fullScreenImageData:(id)data3 croppedImageData:(id)data4 imageView:(id)view;
-(void)imageWasSelected:(id)selected;
-(int)_statusBarOrientationForDeviceOrientation:(int)deviceOrientation;
-(BOOL)showingCameraPreview;
-(BOOL)showCamera;
-(void)setShowCamera:(BOOL)camera;
-(id)cameraButtonBar;
-(CGRect)fullScreenRect;
-(double)durationForTransition:(int)transition;
@end

