/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PhotoLibrary-Structs.h"
#import <TelephonyUI/TPPushButton.h>

@class UIImageView;

@interface TPCameraPushButton : TPPushButton {
	UIImageView* _cameraIcon;
}
// inherited: -(void)dealloc;
-(void)setShowsCameraIcon:(BOOL)icon;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
@end

