/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "NSObject.h"

#import <UIKit/UIToolbar.h>
#ifndef __IPHONE_7_0

@protocol UIToolbarDelegate <NSObject>
@optional
-(id)toolbar:(UIToolbar *)toolbar viewForItem:(UIBarItem *)item;
-(void)toolbar:(UIToolbar *)toolbar willBeginCustomizingItems:(NSArray *)items;
-(void)toolbar:(UIToolbar *)toolbar didBeginCustomizingItems:(NSArray *)items;
-(void)toolbar:(UIToolbar *)toolbar willEndCustomizingItems:(NSArray *)items changed:(BOOL)changed;
-(void)toolbar:(UIToolbar *)toolbar didEndCustomizingItems:(NSArray *)items changed:(BOOL)changed;
@end

#endif
