/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MPSwipableViewDelegate.h"
#import "MPVideoViewController.h"
#import "MediaPlayer-Structs.h"


@interface MPAbstractFullScreenVideoViewController : MPVideoViewController <MPSwipableViewDelegate> {
	unsigned _requestExitAfterHidingControls : 1;
	unsigned _rotateAfterHidingControls : 1;
	unsigned _showControlsAfterRotate : 1;
	unsigned _autoHidingForItemChange : 1;
}
-(id)init;
-(void)dealloc;
-(void)showOverlayIfNecessary;
-(BOOL)canDisplayItem:(id)item withInterfaceOrientation:(int)interfaceOrientation;
-(id)newAlternateTracksTransition;
-(void)displayVideoViewOnScreen;
-(void)loadView;
-(void)setItem:(id)item;
-(BOOL)controlsOverlayVisible;
-(void)setControlsOverlayVisible:(BOOL)visible animate:(BOOL)animate;
-(void)setOrientation:(int)orientation animate:(BOOL)animate;
-(void)setDesiredParts:(unsigned)parts animate:(BOOL)animate;
-(void)setDisabledParts:(unsigned)parts;
-(void)setTVOutEnabled:(BOOL)enabled;
-(void)setVisibleParts:(unsigned)parts animate:(BOOL)animate;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(BOOL)usePosterForTVOut;
-(void)setCanShowControlsOverlay:(BOOL)overlay;
-(void)swipableView:(id)view tappedWithCount:(unsigned)count atLocation:(CGPoint)location;
-(BOOL)transportControls:(id)controls heldButtonPart:(unsigned)part;
-(BOOL)transportControls:(id)controls releasedHeldButtonPart:(unsigned)part;
-(BOOL)transportControls:(id)controls tappedButtonPart:(unsigned)part;
-(void)inactivityMonitorDetectedInactivity:(id)inactivity;
-(void)_bufferingStateChangedNotification:(id)notification;
-(void)playbackStateDidChangeNotification:(id)playbackState;
-(void)itemTypeAvailableNotification:(id)notification;
-(void)transformVideoForInterfaceOrientation:(int)interfaceOrientation animate:(BOOL)animate;
-(BOOL)canHideOverlay:(BOOL)overlay;
-(void)_hideOverlayWithAnimation:(BOOL)animation;
-(void)_hideOverlayWithAnimation:(BOOL)animation shouldUpdateAutohideFlag:(BOOL)flag;
-(void)_setStatusBarVisible:(BOOL)visible duration:(float)duration fenceID:(int)anId;
-(void)_stopWatchingAVController;
-(BOOL)phoneTVOutModeEnabled;
@end

