/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "MPAbstractAlternateTracksViewController.h"

@class UIView, UINavigationBar, UITextLabel, UITableView, UIProgressIndicator;

@interface MPAlternateTracksViewController : MPAbstractAlternateTracksViewController <UITableViewDataSource, UITableViewDelegate> {
	UIView* _backgroundView;
	UINavigationBar* _navigationBar;
	UITableView* _table;
	UIProgressIndicator* _progressIndicator;
	UITextLabel* _loadingLabel;
}
-(void)dealloc;
-(void)didChangeToInterfaceOrientation:(int)interfaceOrientation;
-(void)willChangeToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)_cancelButtonAction:(id)action;
-(void)_doneButtonAction:(id)action;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(void)reloadData;
-(void)addLoadingUI;
-(void)removeLoadingUI;
-(void)_exitAnimated:(BOOL)animated;
-(void)_setCell:(id)cell isChecked:(BOOL)checked;
@end

