/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface MPAlternateTrack : NSObject {
	int _trackID;
	NSString* _languageCode;
	NSString* _name;
}
+(id)copyOffTrack;
+(id)threeCharCodesForEncodedISO639_2_T:(id)encodedISO639_2_T;
-(id)initWithDictionary:(id)dictionary;
-(void)dealloc;
-(int)compare:(id)compare;
-(id)humanReadableLanguage;
-(id)languageCode;
-(id)name;
-(void)setName:(id)name;
-(int)trackID;
@end

