/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MPTransitionController.h"

@class MPVideoViewController, UIImageView;

@interface MPAlternateTracksTransitionController : MPTransitionController {
	MPVideoViewController* _videoController;
	UIImageView* _snapshotCoverImageView;
}
@property(assign, nonatomic) MPVideoViewController* videoController;
-(void)transition:(unsigned)transition;
-(void)_animationDidStop;
@end

