/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import "MPTransportControls.h"

@class UIImage;

@interface MPFullScreenTransportControls : MPTransportControls {
	UIImage* _backgroundImage;
	float _requiredFrameSizeWidth;
}
-(id)init;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
-(id)createVolumeSlider;
-(id)createRouteNameLabel;
-(void)reloadForAdditions:(id)additions removals:(id)removals animate:(BOOL)animate;
-(void)_layoutVolumeSlider:(id)slider;
-(void)_layoutRouteNameLabel:(id)label;
@end

