/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import "MPVideoViewController.h"

@class NSString, UIView, MPInlineVideoOverlay, UIPinchGestureRecognizer, MPWildcatFullScreenVideoOverlay, MPWildcatAudioOverlay, NSTimer, UITapGestureRecognizer;

@interface MPInlineVideoViewController : MPVideoViewController {
@private
	int _videoOverlayStyle;
	MPInlineVideoOverlay* _inlineOverlayView;
	MPWildcatFullScreenVideoOverlay* _fullscreenOverlayView;
	MPWildcatAudioOverlay* _audioOverlayView;
	int _audioOverlayStyle;
	BOOL _overlayViewIsVisible;
	NSString* _playbackErrorDescription;
	UITapGestureRecognizer* _tapGestureRecognizer;
	UITapGestureRecognizer* _doubleTapGestureRecognizer;
	UITapGestureRecognizer* _fullscreenTapGestureRecognizer;
	UITapGestureRecognizer* _fullscreenDoubleTapGestureRecognizer;
	UIPinchGestureRecognizer* _pinchGestureRecognizer;
	UIPinchGestureRecognizer* _fullscreenPinchGestureRecognizer;
	NSTimer* _idleTimer;
	unsigned _wantsOverlayVisibleWhenItemIsAvailable : 1;
	unsigned _wantsOverlayVisibleWhenItemIsAvailableAnimated : 1;
	unsigned _animatingOverlay : 1;
	UIView* _fullscreenView;
	UIView* _superviewBeforeFullscreen;
	unsigned _indexInSuperviewBeforeFullscreen;
	CGRect _nonFullscreenDestinationFrame;
	int _desiredInterfaceOrientation;
	int _previousStatusBarMode;
	unsigned _isFullscreen : 1;
	unsigned _animatingFullscreenTransition : 1;
	unsigned _contentViewDidClipToBounds : 1;
}
@property(assign, nonatomic) int audioOverlayStyle;
@property(copy, nonatomic) NSString* playbackErrorDescription;
@property(assign, nonatomic) int videoOverlayStyle;
@property(readonly, assign, nonatomic) UIView* fullscreenView;
-(id)init;
-(void)dealloc;
-(void)loadView;
-(void)viewDidAppear:(BOOL)view;
-(void)swipableViewHadActivity:(id)activity;
-(void)startTicking;
-(void)stopTicking;
-(void)setItem:(id)item;
-(void)setDesiredParts:(unsigned)parts animate:(BOOL)animate;
-(void)setVisibleParts:(unsigned)parts animate:(BOOL)animate;
-(void)setDisabledParts:(unsigned)parts;
-(id)backgroundView;
-(BOOL)controlsOverlayVisible;
-(void)setControlsOverlayVisible:(BOOL)visible animate:(BOOL)animate;
-(void)setOrientation:(int)orientation animate:(BOOL)animate;
-(void)displayVideoViewOnScreen;
-(void)setControlsNeedLayout;
-(BOOL)isFullscreen;
-(void)setFullscreen:(BOOL)fullscreen animated:(BOOL)animated;
-(void)setDisableControlsAutohide:(BOOL)autohide;
-(void)updateForItemAttributeChanges;
-(void)setItemTypeOverride:(unsigned)override;
-(BOOL)canShowQTAudioOnlyUI;
-(BOOL)transportControls:(id)controls heldButtonPart:(unsigned)part;
-(BOOL)transportControls:(id)controls releasedHeldButtonPart:(unsigned)part;
-(BOOL)transportControls:(id)controls tappedButtonPart:(unsigned)part;
-(void)overlayTappedBackButton:(id)button;
-(void)overlayTappedScaleModeButton:(id)button;
-(void)overlayDidDismissAlternateTracksPopover:(id)overlay;
-(void)_viewWasTapped:(id)tapped;
-(void)_viewWasPinched:(id)pinched;
-(void)_playbackStateDidChangeNotification:(id)_playbackState;
-(void)_itemTypeAvailableNotification:(id)notification;
-(void)_bufferingStateDidChangeNotification:(id)_bufferingState;
-(void)_layoutForItemTypeAvailable;
-(id)_overlayView;
-(id)_overlayViewIfLoaded;
-(id)_audioOverlayViewIfLoaded;
-(BOOL)_canHideOverlay;
-(void)_showOverlayAnimated:(BOOL)animated;
-(void)_showOverlayDidEnd;
-(void)_hideOverlayAnimated:(BOOL)animated;
-(void)_hideOverlayDidEnd:(id)_hideOverlay finished:(id)finished context:(void*)context;
-(void)_fireOverlayIdleTimer:(id)timer;
-(void)_resetOverlayIdleTimer;
-(void)_cancelOverlayIdleTimer;
-(void)_updateForInterfaceOrientation:(int)interfaceOrientation animate:(BOOL)animate;
-(void)_transitionToFullscreenAnimated:(BOOL)fullscreenAnimated;
-(void)_transitionToFullscreenDidEnd;
-(void)_transitionFromFullscreenAnimated:(BOOL)fullscreenAnimated;
-(void)_transitionFromFullscreenDidEnd;
-(unsigned)_effectiveItemType;
-(id)_viewControllerForRotationForViewController:(id)viewController;
-(BOOL)_useInlineControls;
@end

