/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import "MPTransportControls.h"

@class UIActivityIndicatorView, UILabel;

@interface MPInlineTransportControls : MPTransportControls {
@private
	UILabel* _loadingMovieLabel;
	UIActivityIndicatorView* _loadingMovieIndicator;
}
@property(readonly, assign, nonatomic) CGRect availableProgressControlAreaFrame;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)reloadForAdditions:(id)additions removals:(id)removals animate:(BOOL)animate;
-(id)buttonImageForPart:(unsigned)part;
-(id)playButtonImage;
-(id)pauseButtonImage;
-(void)setDisabledParts:(unsigned)parts;
-(void)layoutSubviews;
@end

