/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <Foundation/NSObject.h>
#import "NSCoding.h"

@class MLPlaylist;

@interface MPMediaServerPlaylist : NSObject <NSCoding> {
@private
	MLPlaylist* _playlist;
}
-(id)initWithMLPlaylist:(id)mlplaylist;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)count;
-(id)mediaTypes;
-(id)itemsQuery;
-(id)name;
-(id)playlistAttributes;
-(id)seedItems;
-(id)isWorkoutMix;
@end

