/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <Foundation/NSObject.h>

@class MPMediaItem, MPMediaQuery, NSArray;

@interface MPMediaItemCollectionInternal : NSObject {
@private
	MPMediaQuery* _itemsQuery;
	NSArray* _items;
	unsigned _itemsCount;
	MPMediaItem* _representativeItem;
	int _containedMediaTypes;
}
@end

