/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <MediaPlayer/MPMediaPickerController.h>

@class MPMediaPickerControllerInternal;
@protocol MPMediaPickerControllerDelegate;

@interface MPMediaPickerController ()
+(void)preheatMediaPicker;
-(void)dealloc;
-(void)loadView;
-(void)viewDidUnload;
-(void)viewWillAppear:(BOOL)view;
-(BOOL)_canReloadView;
-(BOOL)scrollViewShouldScrollToTop:(id)scrollView;
-(void)_moveLayerHostToLayer:(id)layer;
-(void)_viewDidMoveToWindow;
-(void)_viewWillMoveFromWindow;
-(void)_viewSizeDidChange;
-(void)_applicationWillTerminate:(id)_application;
-(void)_serverPortInvalidated;
-(void)_invalidateReplyPort;
-(void)_pickerDidCancel;
-(void)_pickerDidPickItems:(id)_picker;
@end

