/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <Foundation/NSObject.h>
#import "MPMediaLibrary.h"

@class MPMediaLibrary;

@interface MPMediaLibraryML : NSObject <MPMediaLibrary> {
@private
	unsigned _filteringDisabled : 1;
	MPMediaLibrary* _mediaLibrary;
}
-(id)init;
-(void)dealloc;
-(void)prepareForQueryingWithMediaLibrary:(id)mediaLibrary;
-(id)serverIsAlive;
-(void)syncDidEnd;
-(void)setFilteringDisabled:(id)disabled;
-(id)hasMedia;
-(id)hasSongs;
-(id)lastModifiedDate;
-(id)itemExistsWithIdentifier:(id)identifier;
-(id)countOfItemsForQuery:(id)query;
-(id)itemsForQuery:(id)query;
-(id)countOfCollectionsForQuery:(id)query;
-(id)collectionsForQuery:(id)query;
-(id)prefetchCommonProperties:(id)properties item:(id)item;
-(id)fetchProperty:(id)property item:(id)item;
-(id)fetchArtworkForSizeValue:(id)sizeValue item:(id)item;
-(id)fetchArtworkForSizeValue:(id)sizeValue atPlaybackTime:(id)playbackTime item:(id)item;
-(id)fetchProperty:(id)property playlist:(id)playlist;
-(id)_collectionsMLQueryForQuery:(id)query;
-(id)_itemsMLQueryForQuery:(id)query;
-(id)_MLQueryForQuery:(id)query;
-(void)_sanitizeQuery:(id)query;
-(void)_availablePlaylistsDidChangeNotification:(id)_availablePlaylists;
@end

