/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <Foundation/NSObject.h>
#import "NSCoding.h"
#import "MediaPlayer-Structs.h"

@class NSDictionary, MLTrack;

@interface MPMediaServerItem : NSObject <NSCoding> {
@private
	MLTrack* _track;
	NSDictionary* _commonProperties;
}
@property(readonly, assign, nonatomic) NSDictionary* commonProperties;
@property(readonly, assign, nonatomic) MLTrack* MLTrack;
-(id)initWithMLTrack:(id)mltrack;
-(id)initWithMLTrack:(id)mltrack prefetchProperties:(BOOL)properties;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)globalID;
-(id)mediaType;
-(id)title;
-(id)albumTitle;
-(id)artist;
-(id)albumArtist;
-(id)genre;
-(id)composer;
-(id)playbackDuration;
-(id)albumTrackNumber;
-(id)albumTrackCount;
-(id)discNumber;
-(id)discCount;
-(id)artwork;
-(id)lyrics;
-(id)isCompilation;
-(id)year;
-(id)releaseDate;
-(id)bpm;
-(id)comments;
-(id)grouping;
-(id)storeItemAdamID;
-(id)artworkDataForSize:(CGSize)size;
-(id)artworkDataForSize:(CGSize)size atPlaybackTime:(double)playbackTime;
-(id)playbackTimesForChapterArtwork;
-(id)podcastTitle;
-(id)seriesName;
-(id)seasonNumber;
-(id)episodeNumber;
-(id)playCount;
-(id)skipCount;
-(id)rating;
-(id)lastPlayedDate;
-(id)sortTitle;
-(id)sortArtist;
-(id)sortAlbumTitle;
-(id)sortAlbumArtist;
-(id)sortComposer;
-(id)chapterDictionaries;
-(id)_newTimeMarkersFromChapterTOC:(id)chapterTOC;
@end

