/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <Foundation/NSObject.h>

@class NSArray;

@interface MPMovieThumbnailRequest : NSObject {
@private
	NSArray* _times;
	int _timeOption;
}
@property(retain, nonatomic) NSArray* times;
@property(assign, nonatomic) int timeOption;
-(void)dealloc;
@end

