/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MPMusicPlayerController.h"
#import "MediaPlayer-Structs.h"
#import "MPServerObjectProxy.h"

@class MPMediaItemCollection, MPMediaQuery;

@interface MPMusicPlayerControllerInternal : MPServerObjectProxy <MPMusicPlayerController> {
@private
	unsigned _clientPort;
	CFRunLoopSourceRef _runLoopSource;
	int _playbackState;
	int _playbackNotificationObservers;
	MPMediaQuery* _query;
	MPMediaItemCollection* _itemCollection;
	unsigned _didCheckIn : 1;
	unsigned _useApplicationSpecificQueue : 1;
	unsigned _useCachedPlaybackState : 1;
	unsigned _cachedPlaybackStateIsValid : 1;
	unsigned _allowsRemoteUIAccess : 1;
	int _inBlockHandlingMessageFromServer;
	int _inBlockHandlingPlaybackStateChangedMessageFromServer;
}
@property(assign) BOOL inBlockHandlingPlaybackStateChangedMessageFromServer;
@property(assign) BOOL inBlockHandlingMessageFromServer;
-(void)prepareForRemoteSelectorInvocation;
-(void)didPrepareForRemoteSelectorInvocation;
-(void)prepareForDecodingWithCoder:(id)coder;
-(void)serverConnectionDied;
@end

