/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import <UIKit/UIView.h>
#import "MPDetailSliderDelegate.h"

@class UILabel, MPItem, MPButton, MPDetailSlider, UIActivityIndicatorView, CABasicAnimation;
@protocol MPPlaybackControlsDelegate;

@interface MPPlaybackControlsView : UIView <MPDetailSliderDelegate> {
	id<MPPlaybackControlsDelegate> _delegate;
	MPItem* _item;
	UIActivityIndicatorView* _activityIndicator;
	MPDetailSlider* _progressControl;
	MPButton* _repeatButton;
	MPButton* _shuffleButton;
	MPButton* _playbackSpeedButton;
	MPButton* _geniusButton;
	MPButton* _rewindButton;
	MPButton* _mailButton;
	UIView* _rewindButtonBezel;
	UILabel* _trackInfoLabel;
	CABasicAnimation* _rewindOpacityAnimation;
	double _progressOffset;
	double _tickInterval;
	unsigned _visibleParts;
	unsigned _wantsTick : 1;
	unsigned _geniusButtonDisabled : 1;
	unsigned _rewindButtonDisabled : 1;
	unsigned _playbackSpeedButtonDisabled : 1;
	unsigned _mailButtonDisabled : 1;
	unsigned _mailButtonHidden : 1;
	unsigned _useMediaDetailSlider : 1;
	unsigned _detailScrubbing : 1;
	float _seekedToValue;
}
@property(assign, nonatomic) id<MPPlaybackControlsDelegate> delegate;
@property(retain, nonatomic) MPItem* item;
@property(assign, nonatomic) unsigned visibleParts;
@property(readonly, assign, nonatomic) unsigned shuffleType;
@property(readonly, assign, nonatomic) unsigned repeatType;
@property(readonly, assign, nonatomic) BOOL hideGeniusButton;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(id)createButtonForPart:(unsigned)part;
-(id)createProgressIndicator;
-(void)handleChangeToRepeatType:(unsigned)repeatType;
-(void)handleChangeToShuffleType:(unsigned)shuffleType;
-(void)reloadView;
-(void)resetDetailSlider:(id)slider;
-(void)startTicking;
-(void)stopTicking;
-(void)setCurrentTime:(double)time;
-(void)updateForEndOfDetailScrubbing;
-(void)didMoveToSuperview;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(void)_geniusButton:(id)button;
-(void)_handleGeniusButtonClick;
-(void)_mailButton:(id)button;
-(void)_playbackSpeedButton:(id)button;
-(void)_repeatButton:(id)button;
-(void)_rewindButton:(id)button;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)_shuffleButton:(id)button;
-(void)detailSliderTrackingDidBegin:(id)detailSliderTracking;
-(void)detailSliderTrackingDidCancel:(id)detailSliderTracking;
-(void)detailSliderTrackingDidEnd:(id)detailSliderTracking;
-(void)detailSlider:(id)slider didChangeValue:(float)value;
-(void)detailSlider:(id)slider didChangeScrubSpeed:(int)speed;
-(void)_contentsChangedNotification:(id)notification;
-(void)crossedChapterTimeMarker:(id)marker;
-(void)crossedArtworkTimeMarker:(id)marker;
-(void)crossedURLTimeMarker:(id)marker;
-(void)_tickNotification:(id)notification;
-(id)_geniusButtonImage:(unsigned)image;
-(void)_initializeControls;
-(id)_mailButtonImage;
-(void)_resetGeniusButtonImages;
-(void)_changeGeniusImageToPressedImage:(id)pressedImage;
-(void)_changeGeniusImageToNormalImage:(id)normalImage;
-(id)_repeatButtonImage;
-(id)_shuffleButtonImage;
-(BOOL)_shuffleIsOn;
-(void)_updateButtonVisibility;
-(void)_updateForPlaybackSpeed;
-(void)_setVisiblePartsNeedReload;
-(void)_reloadVisibleParts;
@end

