/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <Foundation/NSObject.h>

@class NSString, NSURL;

@interface MPTimeMarker : NSObject {
	double _duration;
	unsigned _index;
	id _thumbnail;
	double _time;
	NSString* _title;
	NSURL* _url;
	int _chapterProperty;
}
@property(assign, nonatomic) double duration;
@property(assign, nonatomic) unsigned index;
@property(retain, nonatomic) id thumbnail;
@property(assign, nonatomic) double time;
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSURL* url;
@property(readonly, assign, nonatomic) int chapterProperty;
@property(readonly, assign, nonatomic) double comparableTime;
-(id)initWithChapterProperty:(int)chapterProperty;
-(id)description;
-(void)dealloc;
@end

