/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <UIKit/UIView.h>
#import "MediaPlayer-Structs.h"

@class MPTimeMarker;

@interface MPVideoChapterCellContentView : UIView {
	unsigned _current : 1;
	unsigned _index;
	unsigned _selected : 1;
	unsigned _showThumbnailColumn : 1;
	float _timeColumnWidth;
	MPTimeMarker* _timeMarker;
}
@property(assign, nonatomic) unsigned index;
@property(assign, nonatomic) float timeColumnWidth;
@property(retain, nonatomic) MPTimeMarker* timeMarker;
@property(assign, nonatomic) BOOL showThumbnailColumn;
@property(assign, nonatomic, getter=isSelected) BOOL selected;
@property(assign, nonatomic, getter=isCurrent) BOOL current;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(void)layoutSubviews;
-(BOOL)selected;
-(void)_addThumbnailIfNecessary:(id)necessary;
-(void)_removeThumbnailIfNecessary:(id)necessary;
@end

