/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <Foundation/NSObject.h>

@class MPAudioDeviceController, UILabel, UIButton, MPVolumeSlider;

@interface MPVolumeViewInternal : NSObject {
@private
	MPVolumeSlider* _volumeSlider;
	UIButton* _routeButton;
	UILabel* _routeLabel;
	MPAudioDeviceController* _audioDeviceController;
}
@end

