/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import "MPTransportControls.h"


@interface MPWildcatFullScreenTransportControls : MPTransportControls {
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)reloadForAdditions:(id)additions removals:(id)removals animate:(BOOL)animate;
-(id)createVolumeSlider;
-(id)createRouteNameLabel;
-(id)buttonImageForPart:(unsigned)part;
-(void)setVisibleParts:(unsigned)parts animated:(BOOL)animated;
-(void)setDisabledParts:(unsigned)parts;
-(void)setItem:(id)item;
-(void)layoutSubviews;
-(void)_itemTypeAvailableNotification:(id)notification;
@end

