/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import <UIKit/UINavigationBar.h>


@interface NPCenteringNavigationBar : UINavigationBar {
}
-(CGRect)availableTitleArea;
-(void)_getTitleViewFrame:(CGRect*)frame leftViewFrame:(CGRect*)frame2 rightViewFrame:(CGRect*)frame3 forViews:(id*)views;
-(void)drawRect:(CGRect)rect;
@end

