/**
 * This header is generated by class-dump-z 0.1-11s.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import <UIKit/UIView.h>

@class PSSpecifier;

@interface PSEditingPane : UIView {
	PSSpecifier* _specifier;
	id _delegate;
	unsigned _requiresKeyboard : 1;
}
@property(retain) id preferenceSpecifier;
@property(retain) id preferenceValue;
+(CGSize)defaultSize;
+(id)defaultBackgroundColor;
// inherited: -(id)initWithFrame:(CGRect)frame;
-(BOOL)drawLabel;
-(CGRect)contentRect;
// inherited: -(void)dealloc;
-(void)setDelegate:(id)delegate;
-(BOOL)requiresKeyboard;
-(void)drawPinstripesInRect:(CGRect)rect;
-(id)specifierLabel;
-(void)drawLabelInRect:(CGRect)rect;
-(void)drawRect:(CGRect)rect;
-(BOOL)wantsNewButton;
-(void)addNewValue;
-(void)editMode;
-(void)doneEditing;
-(BOOL)handlesDoneButton;
-(BOOL)changed;
@end

