/**
 * This header is generated by class-dump-z 0.1-11q.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSDictionary, NSString, NSArray;

@interface PSSpecifier : NSObject {
	id target;
	SEL getter;
	SEL setter;
	SEL action;
	Class detailControllerClass;
	int cellType;
	Class editPaneClass;
	int keyboardType;
	int autoCapsType;
	int autoCorrectionType;
	int textFieldType;
	NSString* _name;
	NSArray* _values;
	NSDictionary* _titleDict;
	NSDictionary* _shortTitleDict;
	id _userInfo;
	NSMutableDictionary* _properties;
}
@property(retain) NSMutableDictionary* properties;
@property(retain) NSString* name;
@property(retain) id userInfo;
@property(retain) id titleDictionary;
@property(retain) id shortTitleDictionary;
@property(retain) NSArray* values;
+(id)preferenceSpecifierNamed:(id)named target:(id)target set:(SEL)set get:(SEL)get detail:(Class)detail cell:(int)cell edit:(Class)edit;
+(id)groupSpecifierWithName:(id)name;
+(id)emptyGroupSpecifier;
+(int)autoCapsTypeForString:(id)string;
+(int)keyboardTypeForString:(id)string;
-(id)propertyForKey:(id)key;
-(void)setProperty:(id)property forKey:(id)key;
-(void)removePropertyForKey:(id)key;
-(void)loadValuesAndTitlesFromDataSource;
-(void)setValues:(id)values titles:(id)titles;
-(void)setValues:(id)values titles:(id)titles shortTitles:(id)titles3;
-(void)setupIconImageWithPath:(id)path;
-(id)identifier;
-(void)setTarget:(id)target;
-(void)setKeyboardType:(int)type autoCaps:(int)caps autoCorrection:(int)correction;
-(int)titleCompare:(id)compare;
@end

