/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSDictionary.h>
#import "SpringBoard-Structs.h"


@interface NSDictionary (CTHelpers)
-(id)callClass;
-(id)callForwardingReason;
-(id)callBarringFacility;
-(id)callingLineIDRestrictionValue;
-(id)callingLinePresentationValue;
-(id)connectedLineIDRestrictionValue;
-(id)connectedLinePresentationValue;
-(id)enabledString;
-(id)serviceCenterAddress;
-(id)ssServiceType;
-(id)mmiProcedure;
-(CFStringRef)settingType;
-(id)callingNamePresentationValue;
@end

@interface NSDictionary (SBWiFiAdditions)
-(int)compareNetworkDictionaryAscending:(id)ascending;
@end

@interface NSDictionary (SBOptimizedCombination)
-(id)dictionaryByAddingEntriesFromDictionary:(id)dictionary;
@end

