/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"


@protocol NSObject
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(Class)superclass;
-(Class)class;
-(id)self;
-(NSZone*)zone;
-(id)performSelector:(SEL)selector;
-(id)performSelector:(SEL)selector withObject:(id)object;
-(id)performSelector:(SEL)selector withObject:(id)object withObject:(id)object3;
-(BOOL)isProxy;
-(BOOL)isKindOfClass:(Class)aClass;
-(BOOL)isMemberOfClass:(Class)aClass;
-(BOOL)conformsToProtocol:(id)protocol;
-(BOOL)respondsToSelector:(SEL)selector;
-(id)retain;
-(oneway void)release;
-(id)autorelease;
-(unsigned)retainCount;
-(id)description;
@end

