/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSString.h>
#import <Availability2.h>

@interface NSString (Formatting)
-(id)ICCID;
-(id)IMEI;
@end

#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
@interface NSString (SBDeviceLockEntryFieldExtras)
-(BOOL)isSingleCharacterAndMemberOfSet:(CFCharacterSetRef)set;
-(BOOL)isNewline;
@end
#endif
