/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSDictionary, SBApplication, NSOperationQueue;

@interface SBApplicationController : NSObject {
	NSDictionary* _pendingApplicationDictionaries;
	NSMutableDictionary* _applications;
	NSMutableDictionary* _applicationsByBundleIdentifer;
	SBApplication* _springBoard;
	unsigned _ignoreUninstallationEventCount;
	NSOperationQueue* _backgroundOperationQueue;
}
@property(retain) NSDictionary* pendingApplicationDictionaries;
+(id)sharedInstance;
// inherited: -(id)init;
// inherited: -(void)dealloc;
-(id)allApplications;
-(id)applicationsWithBundleIdentifier:(id)bundleIdentifier;
-(id)applicationWithDisplayIdentifier:(id)displayIdentifier;
-(id)applicationWithPid:(int)pid;
-(id)springBoard;
-(id)iPod;
-(id)loadApplications;
-(void)loadApplicationsAndIcons:(id)icons reveal:(BOOL)reveal popIn:(BOOL)anIn;
-(void)removeApplicationsFromModelWithBundleIdentifier:(id)bundleIdentifier;
-(void)uninstallApplication:(id)application;
-(void)waitForOperationsToComplete;
-(Class)applicationClassForBundleIdentifier:(id)bundleIdentifier;
-(void)loadRolesWithBundle:(id)bundle bundlePath:(id)path isSystemApplication:(BOOL)application defaultTags:(id)tags signerIdentity:(id)identity provisioningProfileValidated:(BOOL)validated seatbeltEnvironmentVariables:(id)variables;
-(void)updateSchemesForRoleDefinition:(id)roleDefinition displayIdentifier:(id)identifier application:(id)application;
-(id)rolesForInfoPlist:(id)infoPlist;
-(id)rolesForRoleDefinitions:(id)roleDefinitions;
-(id)displayNameForInfoDictionary:(id)infoDictionary inBundle:(id)bundle;
-(id)widgetRoles;
-(void)_applicationInstallationCallback:(id)callback;
-(void)_handleInstalledApplicationDictionaryIfReceived;
-(void)processPendingInstalls;
@end

