/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBSlidingAlertDisplay.h"
#import <Availability2.h>
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
#import <UIKit/UITextInput.h>
#endif

@class TPBottomButtonBar, SBNowPlayingArtView, SBAlertImageView, NSTimer, SBAwayViewPluginController, SBAwayChargingView, UIImage, UIModalView, SBAwaySwipeGestureRecognizer, TPBottomLockBar, UIPushButton, NSDictionary, SBAwayDateView, NSString, SBAwayInCallController, SBAwayItemsView, SBActivationView;
@class MPAudioDeviceController, SBAwayLockBar;

@interface SBAwayView : SBSlidingAlertDisplay 
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
<UIKeyInput>
#endif
{
	BOOL _isDimmed;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	BOOL _fullscreen;
	BOOL _alwaysFullscreen;
#endif
	BOOL _deferAwayItemFetching;
	BOOL _showingBlockedIndicator;
	BOOL _hasTelephony;
	BOOL _wasShowingAlertAtDismiss;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	BOOL _awayPluginIsVisible;
	BOOL _ignoreFullScreenUpdates;
#endif
	SBAwayChargingView* _chargingView;
	SBAwayDateView* _dateView;
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_3_2
	SBNowPlayingArtView* _albumArtView;
#endif
	SBAwayItemsView* _awayItemsView;
	SBActivationView* _activationView;
	SBAlertImageView* _firewireWarningView;
	SBAwayViewPluginController* _awayPluginController;
	SBAwaySwipeGestureRecognizer* _gestureRecognizer;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	MPAudioDeviceController* _audioDeviceController;
#endif
	NSTimer* _mediaControlsTimer;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	NSTimer* _fullscreenTimer;
	NSTimer* _chargingViewTimer;
#endif
	NSDictionary* _nowPlayingInfo;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	BOOL _isPlaying;
#else
	UIImage* _nowPlayingArt;
	NSString* _lastTrackArtPath;
#endif
	NSTimer* _blockedStatusUpdateTimer;
	UIModalView* _alertSheet;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	int _alertSheetPosition;
#endif
	SBAwayInCallController* _inCallController;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	SBAwayLockBar* _lockBar;
#else
	TPBottomLockBar* _lockBar;
#endif
	TPBottomButtonBar* _cancelSyncBar;
	UIPushButton* _infoButton;
}
// inherited: +(id)createBottomBarForInstance:(id)instance;
+(id)lockLabels:(BOOL)labels fontSize:(float*)size;
-(void)_clearBlockedStatusUpdateTimer;
// inherited: -(id)initWithFrame:(CGRect)frame;
-(void)postLockCompletedNotification:(BOOL)notification;
// inherited: -(void)dealloc;
-(void)_postLockCompletedNotification;
// inherited: -(void)finishedAnimatingIn;
// inherited: -(void)dismiss;
// inherited: -(void)finishedAnimatingOut;
// inherited: -(float)durationForOthersActivation;
-(void)setBottomLockBar:(id)bar;
// inherited: -(BOOL)shouldAnimateIn;
// inherited: -(BOOL)shouldAnimateIconsOut;
-(void)startAnimations;
-(void)stopAnimations;
-(void)showInfoButton;
-(void)hideInfoButton;
-(void)setLockoutUIVisible:(BOOL)visible mode:(int)mode;
-(void)updateUIForRestorationState:(int)restorationState;
-(void)updateUIForResetState:(int)resetState;
-(void)addFirewireWarningView;
-(void)removeFirewireWarningView;
-(void)updateInterface;
// inherited: -(void)setMiddleContentAlpha:(float)alpha;
-(void)setDimmed:(BOOL)dimmed;
-(BOOL)dimmed;
-(void)lockBarUnlocked:(id)unlocked;
-(void)lockBarStartedTracking:(id)tracking;
-(void)lockBarStoppedTracking:(id)tracking;
-(void)updateLockBarLabel;
-(id)currentAwayPluginController;
-(void)removePluginController:(BOOL)controller;
-(void)_setAwayViewGesturesEnabled:(BOOL)enabled;
-(void)windowGestureWasCompleted:(id)completed;
// inherited: -(BOOL)shouldShowBlockedRedStatus;
-(void)_updateBlockedStatusLabel;
// inherited: -(void)showBlockedStatus;
// inherited: -(void)removeBlockedStatus;
-(void)_updateBlockedStatus;
-(id)dateView;
-(void)removeDateView;
-(void)addDateView;
-(void)awayDateViewDidChangeTitle:(id)awayDateView;
-(id)inCallController;
-(BOOL)shouldShowInCallInfo;
-(void)updateInCallInfo;
-(void)_positionAwayItemsView;
-(void)hideAwayItems;
-(void)showAwayItems;
-(BOOL)hasAwayItems;
// inherited: -(void)setShowingDeviceLock:(BOOL)lock duration:(float)duration;
-(void)showAlertSheet:(id)sheet;
-(void)removeAlertSheet;
-(void)slideAlertSheetOut:(BOOL)anOut direction:(BOOL)direction duration:(float)duration;
-(id)chargingView;
-(void)hideChargingView;
-(void)clearMediaControlsTimer;
-(void)restartMediaControlsTimer;
-(void)hideMediaControls;
-(void)_hideMediaControls;
-(void)showMediaControls;
-(void)toggleMediaControls;
-(BOOL)isShowingMediaControls;
-(id)_topBarLCDControlsImage;
// inherited: -(void)updateTopBarBackground;
-(void)showSyncingBottomBar:(BOOL)bar;
-(void)hideSyncingBottomBar:(BOOL)bar;
-(void)updateNowPlayingInfo:(id)info;
// inherited: -(void)animateToShowingDeviceLock:(BOOL)showingDeviceLock;
-(void)_wirelessModemStateChanged:(id)changed;

#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
// in a protocol: @property(assign, nonatomic) int autocapitalizationType;
// in a protocol: @property(assign, nonatomic) int autocorrectionType;
// in a protocol: @property(assign, nonatomic) int keyboardType;
// in a protocol: @property(assign, nonatomic) int keyboardAppearance;
// in a protocol: @property(assign, nonatomic) int returnKeyType;
// in a protocol: @property(assign, nonatomic) BOOL enablesReturnKeyAutomatically;
// in a protocol: @property(assign, nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
// inherited: -(void)layoutForInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)isAnimating;
-(BOOL)shouldShowChargingView;
-(void)_setMiddleSubviewsAlpha:(float)alpha;
-(void)lockBarUnlocked:(id)unlocked freezeKnobInLockedPosition:(BOOL)lockedPosition;
-(void)_setPluginController:(id)controller;
-(void)_pluginFadeInAnimationDidStop:(id)_pluginFadeInAnimation finished:(BOOL)finished context:(void*)context;
-(void)_fullscreenAnimationStopped:(id)stopped finished:(id)finished context:(void*)context;
-(void)setFullscreen:(BOOL)fullscreen duration:(double)duration force:(BOOL)force;
-(void)setFullscreen:(BOOL)fullscreen duration:(double)duration;
// inherited: -(BOOL)isFullscreen;
-(BOOL)isAlwaysFullscreen;
-(void)setAlwaysFullscreen:(BOOL)fullscreen;
-(void)setIgnoreFullScreenUpdates:(BOOL)updates;
// inherited: -(void)animateToHidingDeviceLockFinished;
-(void)_recenterAlertSheet;
-(void)showChargingView;
-(void)updateChargingView;
-(void)startChargingViewTimer;
-(void)_chargingViewTimerFired;
-(void)_didFadeChargingView;
-(void)clearChargingViewTimer;
-(void)restartMediaControlsTimerIfNecessary;
-(BOOL)isPlaying;
-(void)setPlaying:(BOOL)playing;
-(BOOL)hasNowPlayingInfo;
-(BOOL)hasNowPlayingInfoFromiPod;
-(void)enableOrDisableNowPlayingPlugin;
-(void)_cancelFullscreenTimer;
-(void)_restartFullscreenTimer;
-(void)_fullscreenTimerFired;
-(void)restartFullscreenTimerIfNecessary;
-(BOOL)handleMenuButtonTap;
-(void)didMoveToWindow;
-(void)audioDeviceControllerAudioRoutesChanged:(id)changed;
// inherited: -(BOOL)canBecomeFirstResponder;
// in a protocol: -(BOOL)hasText;
// in a protocol: -(void)insertText:(id)text;
// in a protocol: -(void)deleteBackward;
// inherited: -(void)forwardInvocation:(id)invocation;

#endif
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_3_2
-(void)setDrawsBlackBackground:(BOOL)background;
-(void)_setPluginControllerView:(id)view;
-(void)_batteryStatusChanged:(id)changed;
-(void)addChargingView;
-(void)hideNowPlaying;
-(id)nowPlayingArtView;
-(BOOL)updateNowPlayingArt:(BOOL)art;
-(void)handleRequestedAlbumArt:(id)art;
#endif
@end

