/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIModalView.h>

@class NSArray;

@interface SBAwayItemsView : UIModalView {
	NSArray* _displayedItems;
	float _widestLabel;
}
+(GSFontRef)createItemTypeFont;
// inherited: -(id)init;
// inherited: -(void)dealloc;
-(BOOL)reloadData;
-(id)_labelForAwayItem:(id)awayItem count:(int)count;
-(BOOL)hasAwayItems;
-(void)drawItems;
-(void)drawRect:(CGRect)rect;
@end

