/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBSlidingAlertDisplay.h"


@interface SBCallFailureAlertDisplay : SBSlidingAlertDisplay {
}
// inherited: +(id)createTopBarForInstance:(id)instance;
// inherited: +(id)createBottomBarForInstance:(id)instance;
-(void)ignore:(id)ignore;
-(void)callBack:(id)back;
// inherited: -(void)setAlert:(id)alert;
@end

