/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Availability2.h>

#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_3_2

#import <UIKit/UIWindow.h>

@interface SBCompassRecalibrationControllerWindow : UIWindow {
}
// inherited: -(BOOL)_ignoresHitTest;
@end

#endif
