/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBHUDView.h"
#import <UIKit/UIView.h>
#import <Availability2.h>

@interface SBCompassRecalibrationView :
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
SBHUDView
#else
UIView
#endif
{
}
// inherited: -(id)init;
// inherited: -(void)dealloc;
// -(void)drawRect:(CGRect)rect;
@end

