/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "ISDownloadQueueDelegate.h"

@class ISDownloadQueue;

@interface SBDownloadController : NSObject <ISDownloadQueueDelegate> {
	ISDownloadQueue* _downloadQueue;
}
+(id)sharedInstance;
// inherited: -(id)init;
// inherited: -(void)dealloc;
// in a protocol: -(void)downloadQueue:(id)queue changedWithRemovals:(id)removals disappearances:(id)disappearances;
-(void)_showDownloadQueueError;
// in a protocol: -(void)downloadQueueError:(id)error;
-(BOOL)checkQueue;
-(id)currentDownloads;
-(id)downloadQueue;
-(void)_networkUsageChanged:(id)changed;
@end

