/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIPushButton.h>


@interface SBEmergencyCallButton : UIPushButton {
}
// inherited: +(id)defaultFont;
-(void)drawTitleInRect:(CGRect)rect;
// inherited: -(void)drawButtonPart:(int)part inRect:(CGRect)rect;
@end

