/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIControl.h>
#import <Availability2.h>

@class NSString;

@interface SBIconLabel : UIControl {
	NSString* _label;
	unsigned _drawMoreLegibly : 1;
	unsigned _inDock : 1;
	unsigned _ellipsesText : 1;
	unsigned _kerningAllowed : 1;
	unsigned _textMightOverlap : 1;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	unsigned _onWallpaper : 1;
#endif
}
-(id)initWithSize:(CGSize)size label:(NSString *)label;
// inherited: -(void)dealloc;
-(void)setInDock:(BOOL)dock;
-(void)setDisplaysOnWallpaper:(BOOL)wallpaper __OSX_AVAILABLE_STARTING( _MAC_NA, __IPHONE_3_2);
-(void)setEllipsesText:(BOOL)text;
-(void)setKerningAllowed:(BOOL)allowed;
-(void)drawRect:(CGRect)rect;
@end

