/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBIconListPageControlDelegate.h"
#import "UIScrollViewDelegate.h"
#import <UIKit/UIKit.h>
#import <Availability2.h>

@class UITouch, SBIconListPageControl, SBIcon, SBIconScrollView, SBIconList, UIView, NSTimer, SBSearchView, SBIconModel, TPLCDTextView, SBIconContentView;

@interface SBIconController : NSObject <UIScrollViewDelegate, SBIconListPageControlDelegate> {
	SBIconModel* _iconModel;
	UIView* _contentView;
	SBIconScrollView* _scrollView;
	SBIconListPageControl* _pageControl;
	int _currentIconListIndex;
	int _currentColumnIndex;
	TPLCDTextView* _idleText;
	float _currentIdleTextOffset;
	SBSearchView* _searchView;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	int _orientation;
#endif
	SBIcon* _lastClickedIcon;
	double _lastClickedTime;
	SBIcon* _iconToInstall;
	SBIcon* _grabbedIcon;
	SBIconList* _grabbedIconList;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	int _grabbedIndex;
#endif
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_3_2
	int _grabbedX;
	int _grabbedY;
#endif
	SBIcon* _swappedIcon;
	SBIconList* _swappedIconList;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	int _swappedIndex;
#endif
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_3_2
	int _swappedX;
	int _swappedY;
#endif
	SBIconList* _destinationIconList;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	int _destinationIndex;
#endif
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_3_2
	int _destinationX;
	int _destinationY;
#endif
	NSTimer* _scrollPageTimer;
	unsigned _didScroll : 1;
	unsigned _isEditing : 1;
	unsigned _compacted : 1;
	unsigned _willSwap : 1;
	unsigned _animatedScrolling : 1;
	unsigned _scrollingToSearch : 1;
	unsigned _movedFromOrigin : 1;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	unsigned _disableUpdatingCurrentIconList : 1;
	unsigned _delayResumingAutorotation : 1;
	unsigned _onWallpaper : 1;
#endif
	float _iconAlpha;
	float _searchViewAlpha;
	UITouch* _lastTouch;
}
+(SBIconController*)sharedInstance;
// inherited: -(id)init;
// inherited: -(void)dealloc;
-(SBIconContentView*)contentView;
-(void)setPageControlVisible:(BOOL)visible;
-(void)showInfoAlertIfNeeded;
-(void)showCarrierDebuggingAlertIfNeeded;
-(BOOL)isScrolling;
// in a protocol: -(void)pageControl:(id)control didRecieveTouchInDirection:(int)direction;
-(int)lowestVisibleIconListIndexAndColumnIndex:(int*)index;
-(void)updateCurrentIconListIndex;
-(void)resetCurrentVisibleIconListImageVisibilityAndJitterState;
-(SBIconList*)currentIconList;
-(BOOL)isShowingSearch;
-(int)currentIconListIndex;
-(void)scrollToIconListContainingIcon:(SBIcon*)iconListContainingIcon animate:(BOOL)animate;
-(void)scrollToIconListAtIndex:(NSInteger)index animate:(BOOL)animate;
-(void)updateContentSize;
-(void)noteNumberOfIconListsChanged;
-(void)removeEmptyIconList:(id)list animate:(BOOL)animate;
-(SBIcon *)iconToInstall;
-(void)setIconToInstall:(SBIcon *)icon;
-(void)finishInstallingIcon;
-(void)scrollToIconDestination;
-(void)removeIcon:(SBIcon *)icon animate:(BOOL)animate;
-(void)uninstallIcon:(SBIcon *)icon;
-(void)uninstallIcon:(SBIcon *)icon animate:(BOOL)animate;
-(void)lcdTextViewCompletedScroll:(id)scroll;
-(void)idleTextDidAnimate:(id)idleText finished:(id)finished toText:(id)text;
-(void)updateNumberOfRowsWithDuration:(float)duration;
-(BOOL)hasIdleModeText;
-(void)setIdleModeText:(NSString *)text;
-(void)adjustIconListAlpha;
-(void)_showSearchKeyboardIfNecessary:(BOOL)necessary;
// in a protocol: -(void)scrollViewDidScroll:(id)scrollView;
// in a protocol: -(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
// in a protocol: -(void)scrollViewWillBeginDecelerating:(id)scrollView;
// in a protocol: -(void)scrollViewDidEndDecelerating:(id)scrollView;
// in a protocol: -(void)scrollViewDidEndScrollingAnimation:(id)scrollView;
-(void)launchIcon:(SBIcon *)icon;
-(void)doubleClickedIcon:(SBIcon *)icon;
-(void)clickedIcon:(SBIcon *)icon;
-(int)reorderCount;
-(void)incrementReorderCount;
-(void)_addEmptyListIfNecessary;
-(void)setIsEditing:(BOOL)editing;
-(BOOL)isEditing;
-(SBIcon *)iconAnimationView;
-(void)moveIconToWindow:(UIWindow *)window;
-(void)moveIconFromWindow:(UIWindow *)window toIconList:(SBIcon *)iconList;
-(void)ungrabAnimation:(id)animation didFinish:(id)finish grabbedIcon:(SBIcon *)icon;
-(void)noteDownloadStateChanged;
-(void)noteViewCovered;
-(void)setLastTouch:(UITouch *)touch;
-(void)fixupBouncedIconsAfterIndex:(NSInteger)index;
-(void)setGrabbedIcon:(SBIcon *)icon;
-(SBIcon *)grabbedIcon;
-(SBIconList *)destinationIconList;
-(void)cancelScrollTimer;
-(void)scrollLeft;
-(void)scrollRight;
-(void)noteGrabbedIconLocationChangedWithTouch:(UITouch *)touch;
-(void)noteGrabbedIconLocationChangedWithEvent:(UIEvent *)event;
-(void)compactIconsInIconLists:(BOOL)iconLists limitToIconList:(SBIcon *)iconList;
-(void)animateToNewState:(float)newState domino:(BOOL)domino;
-(void)moveAnimation:(id)animation didFinish:(id)finish movePlan:(id)plan;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
-(UIScrollView *)scrollView;
-(UIInterfaceOrientation)orientation;
-(void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation duration:(NSTimeInterval)duration;
-(void)willAnimateRotationToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation duration:(NSTimeInterval)duration;
-(void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation;
-(void)updateIconListFrames;
-(void)updateIconListWallpaperState;
-(void)setIconsDisplayOnWallpaper:(BOOL)wallpaper;
-(id)addIcon:(SBIcon *)icon toIconList:(SBIcon *)iconList index:(NSInteger)index animate:(BOOL)animate moveNow:(BOOL)now scrollToList:(BOOL)list;
-(id)insertIcon:(SBIcon *)icon intoIconList:(id)list index:(NSInteger)index moveNow:(BOOL)now duration:(float)duration;
-(void)uninstallIconDidAnimate:(id)uninstallIcon finished:(id)finished icons:(SBIcon *)icons;
-(void)scatterWithDuration:(NSTimeInterval)duration startTime:(double)time;
-(void)unscatterWithDuration:(NSTimeInterval)duration startTime:(double)time;
-(void)unscatterWithDuration:(NSTimeInterval)duration startTime:(double)time fade:(BOOL)shouldFade;
-(void)resumeRotationDelayed;
-(void)moveIcon:(SBIcon *)icon fromIconList:(SBIconList *)sourceIconList toIndex:(NSInteger)index toIconList:(SBIconList *)destIconList animate:(BOOL)animate;
-(void)moveIcon:(SBIcon *)icon fromIconList:(SBIconList *)sourceIconList toIndex:(NSInteger)index toIconList:(SBIconList *)destIconList;
#endif
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_3_2
-(id)addIcon:(SBIcon *)icon toIconList:(SBIconList *)iconList x:(NSInteger)x y:(NSInteger)y animate:(BOOL)animate moveNow:(BOOL)now scrollToList:(BOOL)list;
-(id)insertIcon:(SBIcon *)icon intoIconList:(SBIconList *)iconList X:(NSInteger)x Y:(NSInteger)y moveNow:(BOOL)now duration:(float)duration;
-(void)uninstallIconDidAnimate:(id)uninstallIcon finished:(id)finished icon:(SBIcon *)icon;
-(void)scatter:(BOOL)scatter startTime:(NSTimeInterval)time;
-(void)unscatter:(BOOL)unscatter startTime:(NSTimeInterval)time;
-(void)moveIcon:(SBIcon *)icon fromIconList:(SBIconList *)sourceIconList toX:(NSInteger)x Y:(NSInteger)y toIconList:(SBIconList *)destIconList animate:(BOOL)animate;
-(void)moveIcon:(SBIcon *)icon fromIconList:(SBIconList *)sourceIconList toX:(NSInteger)x Y:(NSInteger)y toIconList:(SBIconList *)destIconList;
#endif
@end

