/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, SBDismissOnlyAlertItem;

@interface SBLockdownManager : NSObject {
	int _state;
	BOOL _settingUpActivationState;
	BOOL _isBricked;
	BOOL _isInternalInstall;
	BOOL _hasShownWaitingAlertThisSession;
	BOOL _hasShownMismatchedSIM;
	SBDismissOnlyAlertItem* _activatingAlertItem;
	NSString* _unqiueDeviceIdentifier;
}
+(id)sharedInstance;
-(BOOL)_hasEverRegistered;
-(void)_setHasEverRegistered:(BOOL)registered;
-(BOOL)_isRegisteredToNetwork;
-(void)_setCurrentAlertItem:(id)item;
-(BOOL)_shouldShowTelephonyAlerts;
-(void)_postAlertsIfNeeded;
-(void)_resetActivationState;
-(void)_activationFailed;
-(void)_serviceAvailabilityChanged:(id)changed;
-(void)_setupActivationState;
-(BOOL)brickedDevice;
-(BOOL)isInternalInstall;
-(int)lockdownState;
-(id)uniqueDeviceIdentifier;
-(id)valueForDomain:(id)domain key:(id)key;
@end

