/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


@interface SBNetworkReselectionAlert : SBAlert {
}
// inherited: +(void)registerForAlerts;
// inherited: +(void)test;
@end

