/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBWaveView.h"


@interface SBPathWaveView : SBWaveView {
}
-(id)_shapeLayer;
-(CGPathRef)_copyCurrentPath;
-(void)_updateCurrentPath;
-(void)layoutSubviews;
@end

