/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"

@class SBApplication;

@interface SBRemoteNotificationEnableSystemwideAlert : SBAlertItem {
	SBApplication* _app;
}
-(id)initWithApplication:(id)application;
// inherited: -(void)dealloc;
-(void)_showNotificationsPrefs;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
// inherited: -(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
// inherited: -(BOOL)shouldShowInLockScreen;
@end

