/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class NSTimer, SBResetProgressView;

@interface SBResetView : UIView {
	SBResetProgressView* _progressView;
	NSTimer* _progressTimer;
}
// inherited: -(id)initWithFrame:(CGRect)frame;
// inherited: -(void)dealloc;
-(void)_resetStarted:(id)started;
-(void)_resetFinished:(id)finished;
-(void)_updateProgress;
@end

