/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/Foundation.h>
#import <Availability2.h>

@interface SBSheetController : NSObject {
	NSMutableDictionary* _appToSheetMap;
	UIWindow* _presentationWindow;
}
+(SBSheetController *)sharedInstance;
// inherited: -(id)init;
// inherited: -(void)dealloc;
-(void)animateSheetUp:(id)up;
-(void)animationDidStop:(id)animation finished:(id)finished context:(void*)context;
-(void)animateSheetDown:(id)down;
-(void)dismissRemoteViewIdentifier:(id)identifier forApplication:(id)application;
-(BOOL)isShowingSheets;
-(void)dismissAllSheets;
-(void)dismissSheetsForApplication:(id)application;
-(BOOL)sheetWantsProgress;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
-(BOOL)presentRemoteViewIdentifier:(id)identifier asSheetForApplication:(id)application requireTopApplication:(BOOL)application3;
-(void)sendDeviceOrientationChangesToSheets;
-(void)sendStatusBarOrientationWillChangeToSheets:(int)sendStatusBarOrientation duration:(float)duration;
#endif
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_3_2
-(BOOL)presentRemoteViewIdentifier:(id)identifier asSheetForApplication:(id)application;
#endif
@end

