/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"


@interface SBSIMLockAlertItem : SBAlertItem {
	int _status;
}
+(id)alertTitleForStatus:(int)status languageCode:(id)code;
+(id)alertTitleForStatus:(int)status;
-(id)initWithStatus:(int)status;
// inherited: -(void)dealloc;
-(BOOL)canUnlock;
-(id)alertTitleForLanguageCode:(id)languageCode;
-(id)alertTextForLanguageCode:(id)languageCode;
-(int)status;
// inherited: -(void)didDeactivateForReason:(int)reason;
-(void)unlock;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
// inherited: -(void)performUnlockAction;
// inherited: -(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
// inherited: -(id)lockLabel;
@end

