/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"

@class NSString, CKMessage;

@interface SBSMSAlertItem : SBAlertItem {
	CKMessage* _message;
	int _alignment;
	BOOL _alignmentHasBeenSet;
	BOOL _displayingEntireMessage;
	BOOL _playedSound;
	NSString* _name;
}
+(BOOL)shouldPlayMessageReceived;
+(void)playMessageReceived;
+(void)prefsChanged;
+(BOOL)_showSMSPreview;
+(BOOL)shouldHideSMSPreview;
-(void)_tag;
-(void)_untag;
-(void)_deactivateAllTaggedSMSAlertItems;
-(void)setMessage:(id)message;
-(void)willPresentAlertSheet:(id)sheet;
-(id)address;
-(id)name;
-(BOOL)senderIsVoicemail;
-(BOOL)hasAttachments;
-(id)messageText;
-(id)alertImageData;
-(int)_groupID;
-(void)reply;
-(void)_markReadIfDisplayingEntireMessage;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(int)bodyTextAlignmentForAlertSheet:(id)alertSheet displayedLineCount:(int)count;
@end

