/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBStatusBarContentView.h"


@interface SBStatusBarBluetoothBatteryView : SBStatusBarContentView {
	BOOL _showBluetoothBatteryView;
}
// inherited: -(id)init;
// inherited: -(void)start;
// inherited: -(void)stop;
-(void)batteryLevelChanged;
-(void)drawRect:(CGRect)rect;
// inherited: -(int)priority;
// inherited: -(void)setVisible:(BOOL)visible;
// inherited: -(BOOL)isVisible;
// inherited: -(float)padding;
@end

