/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBStatusBarContentView.h"


@interface SBStatusBarAirPortView : SBStatusBarContentView {
	int _dataConnectionType;
	int _signalStrength;
	unsigned _showsAirPortBars : 1;
	unsigned _showsCellDataIndicator : 1;
	unsigned _isPolling : 1;
	unsigned _didSetIndicatorFlags : 1;
	BOOL _showsAirPortView;
	float _overlap;
}
// inherited: -(id)init;
// inherited: -(void)dealloc;
// inherited: -(void)start;
// inherited: -(void)stop;
-(void)setAirPortStrength:(int)strength;
-(void)setShowsAirPortBars:(BOOL)bars;
-(void)setShowsCellDataIndicator:(BOOL)indicator;
-(void)setDataConnectionType:(int)type;
-(BOOL)showsIndicator;
-(void)dataConnectionTypeChanged;
// inherited: -(int)priority;
-(void)drawRect:(CGRect)rect;
// inherited: -(void)touchesEnded:(id)ended withEvent:(id)event;
// inherited: -(void)setVisible:(BOOL)visible;
// inherited: -(BOOL)isVisible;
// inherited: -(float)padding;
// inherited: -(void)setOverlap:(float)overlap;
// inherited: -(float)overlap;
@end

