/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBDismissOnlyAlertItem.h"


@interface SBVoiceMailAlertItem : SBDismissOnlyAlertItem {
	BOOL _isForVisualVoicemail;
	unsigned _recordUID;
}
+(id)currentInstance;
+(BOOL)hasCurrentInstance;
-(BOOL)isForVisualVoicemail;
-(void)setIsVisualVoicemail:(BOOL)voicemail recordUID:(unsigned)uid;
@end

