/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "Message-Structs.h"
#import "WeaklyReferencedObject.h"
#import <AccountSettings/BasicAccount.h>

@class NSString;

@interface Account : BasicAccount <WeaklyReferencedObject> {
	unsigned _isOffline : 1;
	unsigned _autosynchronizingEnabled : 1;
	unsigned _isActive : 2;
}
// inherited: +(void)initialize;
+(NSDictionary*)basicAccountProperties;	// {Type="MobileMe"; "Type String"="MobileMe"; "Short Type String"="MobileMe"; Class="iToolsAccount"};
+(id)createAccountWithDictionary:(id)dictionary;
+(BOOL)haveAccountsBeenConfigured;
+(BOOL)isPredefinedAccountType;
+(id)predefinedValueForKey:(id)key;
+(NSArray*)supportedDataclasses;	// NSArray of NSStrings
+(id)readAccountsUsingKey:(id)key;
+(void)saveAccounts:(id)accounts usingKey:(id)key;
+(void)saveAccountInfoToDefaults;
+(NSString*)accountTypeString;
+(NSString*)displayedAccountTypeString;
+(NSString*)displayedShortAccountTypeString;
+(NSString*)myFullName;
+(id)accountPropertiesValueForKey:(id)key value:(id)value;
+(BOOL)allObjectsInArrayAreOffline:(id)arrayAreOffline;
+(NSString*)hostname;
+(BOOL)isSSLEditable;
+(id)saslProfileName;
// inherited: -(id)init;
-(void)_initializeState;
-(id)initWithBasicAccount:(id)basicAccount;
-(id)_initWithProperties:(id)properties;
// in a protocol: -(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
// in a protocol: -(id)retain;
-(void)release;
// in a protocol: -(unsigned)retainCount;
-(void)setAutosynchronizingEnabled:(BOOL)enabled;
-(void)_queueAccountInfoDidChange;
// inherited: -(id)propertiesToSave;
-(void)_setAccountProperties:(id)properties;
-(void)setValueInAccountProperties:(id)accountProperties forKey:(id)key;
-(void)removeValueInAccountPropertiesForKey:(id)key;
-(id)valueInAccountPropertiesForKey:(id)key;
-(BOOL)isActive;
-(void)setIsActive:(BOOL)active;
-(BOOL)canGoOffline;
-(BOOL)isOffline;
-(void)setIsOffline:(BOOL)offline;
// inherited: -(id)displayName;
-(void)setDisplayName:(id)name;
-(id)username;
-(void)setUsername:(id)username;
-(id)hostname;
-(void)setHostname:(id)hostname;
-(void)setPasswordInKeychain:(id)keychain;
-(void)_removePasswordInKeychain;
-(void)setTemporaryPassword:(id)password;
-(void)setPassword:(id)password;
-(id)passwordFromStoredUserInfo;
-(id)passwordFromKeychain;
-(id)password;
-(id)promptUserForPasswordWithMessage:(id)message;
-(BOOL)storesPassword;
-(BOOL)needsCredentials;
-(BOOL)acquireCredentialsWithPassword:(id)password;
-(id)managedTag;
-(id)promptUserIfNeededForPasswordWithMessage:(id)message;
-(unsigned)portNumber;
-(unsigned)defaultPortNumber;
-(unsigned)defaultSecurePortNumber;
-(unsigned)keychainPortNumber;
-(void)setPortNumber:(unsigned)number;
-(BOOL)isCommonPortNumber:(unsigned)number;
-(id)serviceName;
-(id)secureServiceName;
-(CFStringRef)connectionServiceType;
-(void)releaseAllConnections;
-(void)releaseAllForcedConnections;
-(void)validateConnections;
-(BOOL)usesSSL;
-(void)setUsesSSL:(BOOL)ssl;
-(void)setTryDirectSSL:(BOOL)ssl;
-(id)domain;
-(void)setDomain:(id)domain;
-(void)accountInfoDidChange;
-(id)preferredAuthScheme;
-(void)setPreferredAuthScheme:(id)scheme;
-(id)_createConnection;
-(Class)connectionClass;
-(BOOL)requiresAuthentication;
-(id)authenticatedConnection;
-(id)defaultConnectionSettings;
-(void)applySettingsAsDefault:(id)aDefault;
-(id)alternateConnectionSettings;
-(id)insecureConnectionSettings;
-(id)secureConnectionSettings;
-(BOOL)_shouldTryDirectSSLConnectionOnPort:(unsigned)port;
-(id)customTitleForError:(id)error authScheme:(id)scheme defaultTitle:(id)title;
-(id)customTitleForAuthenticationError:(id)authenticationError authScheme:(id)scheme defaultTitle:(id)title;
-(id)customDescriptionForError:(id)error authScheme:(id)scheme defaultDescription:(id)description;
-(BOOL)isPasswordMissing;
-(void)reportAuthenticationError:(id)error authScheme:(id)scheme;
-(BOOL)_connectAndAuthenticate:(id)authenticate;
-(id)uniqueId;
// inherited: -(id)syncStoreIdentifier;
-(id)nameForMailboxUid:(id)mailboxUid;
-(void)setUserApprovedCertificateDigest:(id)digest;
-(id)userApprovedCertificateDigest;
-(BOOL)shouldEnableAfterError:(id)error;
-(BOOL)enableAccount;
-(BOOL)shouldDisplayHostnameInErrorMessages;
-(id)missingPasswordErrorWithTitle:(id)title;
@end

