/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "AuthScheme.h"


@interface APOPAuthScheme : AuthScheme {
}
-(BOOL)supportsAccountType:(id)type;
// inherited: -(Class)connectionClassForAccountClass:(Class)accountClass;
// inherited: -(Class)authenticatorClassForAccountClass:(Class)accountClass;
// inherited: -(BOOL)hasEncryption;
// inherited: -(BOOL)requiresPassword;
// inherited: -(BOOL)requiresDomain;
// inherited: -(id)name;
// inherited: -(id)humanReadableName;
// inherited: -(BOOL)canAuthenticateAccountClass:(Class)aClass connection:(id)connection;
@end

