/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "Message-Structs.h"
#import <Foundation/NSObject.h>
#import "Connection.h"

@class NSData, NSMutableString, _NSSocket;
@protocol SASLSecurityLayer;

@interface Connection : NSObject {
	id<SASLSecurityLayer> _securityLayer;
	_NSSocket* _socket;
	char* _buffer;
	int _bufferRemainingBytes;
	unsigned _bufferStart;
	unsigned _bufferLength;
	unsigned _desiredBufferLength;
	NSData* _logData;
	unsigned _dontLogReads;
	unsigned _readBytesNotLogged;
	NSMutableString* _readBytesToLog;
	unsigned _isFetching : 1;
	unsigned _allowFallbacks : 1;
}
+(void)readLoggingDefaults;
// inherited: +(void)initialize;
+(void)logBytes:(const char*)bytes length:(int)length;
+(void)flushLog;
+(id)logClasses;
+(void)setLogClasses:(id)classes;
+(BOOL)logAllSocketActivity;
+(void)setLogAllSocketActivity:(BOOL)activity;
+(id)logActivityOnPorts;
+(void)setLogActivityOnPorts:(id)ports;
+(id)logActivityOnHosts;
+(void)setLogActivityOnHosts:(id)hosts;
+(BOOL)shouldTryFallbacksAfterError:(id)error;
// inherited: -(void)dealloc;
-(BOOL)isForcedConnection;
-(BOOL)isFetching;
-(void)setIsFetching:(BOOL)fetching;
-(BOOL)connectUsingSettings:(id)settings;
-(BOOL)connectUsingAccount:(id)account;
-(BOOL)connectUsingFallbacksForAccount:(id)account;
-(void)setAllowsFallbacks:(BOOL)fallbacks;
-(BOOL)authenticateUsingAccount:(id)account;
-(id)capabilities;
-(id)authenticationMechanisms;
-(BOOL)writeData:(id)data dontLogBytesInRange:(NSRange)range;
-(BOOL)writeData:(id)data;
-(void)setDesiredReadBufferLength:(unsigned)length;
-(void)enableReadLogging:(BOOL)logging;
-(void)logReadChars:(const char*)chars length:(unsigned)length;
-(BOOL)readLineIntoData:(id)data;
-(BOOL)readBytesIntoData:(id)data desiredLength:(unsigned)length;
-(BOOL)authenticateUsingAccount:(id)account authenticator:(id)authenticator;
-(BOOL)startTLSForAccount:(id)account;
-(BOOL)isValid;
-(void)disconnect;
-(void*)_socket;
-(BOOL)hasBytesAvailable;
-(id)_createSocket;
-(double)lastUsedTime;
@end

@interface Connection (Gross)
-(id)_nssocket;
@end

