/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Foundation/NSObject.h>
#import "Message-Structs.h"

@class NSData, NSString;

@interface ConnectionSettings : NSObject {
	NSString* _hostname;
	NSString* _serviceName;
	unsigned _portNumber;
	NSData* _serverCertificateDigest;
	CFStringRef _connectionServiceType;
	unsigned _usesSSL : 1;
	unsigned _tryDirectSSLConnection : 1;
}
// inherited: -(void)dealloc;
-(id)hostname;
-(void)setHostname:(id)hostname;
-(id)serviceName;
-(void)setServiceName:(id)name;
-(unsigned)portNumber;
-(void)setPortNumber:(unsigned)number;
-(BOOL)usesSSL;
-(void)setUsesSSL:(BOOL)ssl;
-(BOOL)tryDirectSSL;
-(void)setTryDirectSSL:(BOOL)ssl;
-(CFStringRef)connectionServiceType;
-(void)setConnectionServiceType:(CFStringRef)type;
-(id)serverCertificateDigest;
-(void)setServerCertificateDigest:(id)digest;
// inherited: -(id)description;
@end

