/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Foundation/NSObject.h>
#import "DAMFStreamingContentConsumer.h"

@class NSMutableData;
@protocol DataConsumer, MessageDataConsumerFactory;

@interface DAMessageContentConsumer : NSObject <DAMFStreamingContentConsumer> {
	int _requestedFormat;
	id<DataConsumer> _dataConsumer;
	id<DataConsumer> _alternatePartConsumer;
	id<MessageDataConsumerFactory> _consumerFactory;
	BOOL _triedCreatingAlternatePartConsumer;
	BOOL _succeeded;
	NSMutableData* _bodyData;
	double _timeOfLastActivity;
}
@property(retain, nonatomic) id<DataConsumer> dataConsumer;
@property(retain, nonatomic) id<DataConsumer> alternatePartConsumer;
@property(readonly, retain, nonatomic) NSMutableData* bodyData;
@property(retain, nonatomic) id<MessageDataConsumerFactory> consumerFactory;
@property(assign, nonatomic) int requestedFormat;
@property(readonly, assign, nonatomic) double timeOfLastActivity;
// in a protocol: -(BOOL)shouldBeginStreamingForMailMessage:(id)mailMessage format:(int)format;
// in a protocol: -(void)consumeData:(char*)data length:(int)length format:(int)format mailMessage:(id)message;
// in a protocol: -(void)didEndStreamingForMailMessage:(id)mailMessage;
// in a protocol: -(id)data;
// in a protocol: -(BOOL)succeeded;
-(id)dataConsumerForPart:(id)part;
// inherited: -(void)dealloc;
@end

