/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "DAMailboxStreamingContentConsumer.h"
#import "DAMailboxFetchSearchResultConsumer.h"
#import <Foundation/NSObject.h>

@class MFError, MFConditionLock;
@protocol DAMFStreamingContentConsumer;

@interface DAMessageStoreSearchResultBodyConsumer : NSObject <DAMailboxFetchSearchResultConsumer, DAMailboxStreamingContentConsumer> {
	MFConditionLock* _doneCondition;
	id<DAMFStreamingContentConsumer> _streamConsumer;
	MFError* _error;
}
@property(retain, nonatomic) MFError* error;
@property(retain, nonatomic) id<DAMFStreamingContentConsumer> streamConsumer;
// inherited: -(id)init;
-(BOOL)waitUntilDoneBeforeDate:(id)date;
-(void)waitUntilDone;
// in a protocol: -(void)actionFailed:(int)failed forTask:(id)task error:(id)error;
// in a protocol: -(void)searchResultFetchedWithResponses:(id)responses;
// in a protocol: -(BOOL)shouldBeginStreamingForMailMessage:(id)mailMessage format:(int)format;
// in a protocol: -(void)consumeData:(char*)data length:(int)length format:(int)format mailMessage:(id)message;
// in a protocol: -(void)didEndStreamingForMailMessage:(id)mailMessage;
// inherited: -(void)dealloc;
@end

