/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "BufferedQueue.h"

@class ActivityMonitor, DAMessageStore, MFError, MailMessageLibrary, DAMailbox;

@interface DAMSBasicConsumer : BufferedQueue {
	DAMailbox* mailbox;
	DAMessageStore* store;
	MailMessageLibrary* library;
	ActivityMonitor* monitor;
	int numNewMessages;
	MFError* error;
}
@property(retain, nonatomic) ActivityMonitor* monitor;
@property(retain, nonatomic) MFError* error;
// inherited: -(id)init;
// inherited: -(void)dealloc;
@end

