/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "Message-Structs.h"
#import "MailMessage.h"

@class NSArray;

@interface IMAPMessage : MailMessage {
	unsigned _size;
	XXStruct_vs6POB _imapFlags;
	NSArray* _customFlags;
	unsigned _uid;
}
// inherited: +(void)initialize;
-(id)initWithFlags:(unsigned long)flags customFlags:(id)flags2 size:(unsigned)size uid:(unsigned long)uid;
// inherited: -(void)dealloc;
// inherited: -(id)description;
// inherited: -(unsigned)messageSize;
// inherited: -(id)messageID;
-(int)compareByNumberWithMessage:(id)message;
// inherited: -(unsigned long)uid;
-(void)setUid:(unsigned long)uid;
-(BOOL)isPartial;
-(void)setIsPartial:(BOOL)partial;
// inherited: -(BOOL)isMessageContentsLocallyAvailable;
// inherited: -(void)setPreferredEncoding:(unsigned long)encoding;
-(BOOL)hasTemporaryUid;
-(void)setHasTemporaryUid:(BOOL)uid;
-(XXStruct_vs6POB)imapFlags;
-(id)customFlags;
-(id)mailboxName;
// inherited: -(id)remoteID;
// inherited: -(id)remoteMailboxURL;
// inherited: -(id)originalMailboxURL;
@end

