/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "MailAccount.h"


@interface LocalAccount : MailAccount {
}
+(id)localAccount;
// inherited: +(id)accountTypeString;
// inherited: -(id)initWithPath:(id)path;
// inherited: -(id)uniqueId;
// inherited: -(Class)storeClass;
// inherited: -(id)mailboxPathExtension;
// inherited: -(id)primaryMailboxUid;
// inherited: -(void)setPath:(id)path;
// inherited: -(id)displayName;
// inherited: -(void)setHostname:(id)hostname;
// inherited: -(void)setUsername:(id)username;
-(id)password:(BOOL)password;
// inherited: -(void)setPassword:(id)password;
// inherited: -(BOOL)canFetch;
// inherited: -(int)fetchSynchronously;
// inherited: -(BOOL)isOffline;
// inherited: -(void)setIsOffline:(BOOL)offline;
-(void)_synchronouslyLoadListingForParent:(id)parent;
-(id)_copyMailboxUidWithParent:(id)parent name:(id)name attributes:(unsigned)attributes existingMailboxUid:(id)uid permanentTag:(id)tag dictionary:(id)dictionary;
-(BOOL)_setChildren:(id)children forMailboxUid:(id)mailboxUid;
// inherited: -(BOOL)renameMailbox:(id)mailbox newName:(id)name parent:(id)parent;
-(id)mailboxUidForFileSystemPath:(id)fileSystemPath;
-(id)_URLScheme;
-(id)_infoForMatchingURL:(id)matchingURL;
@end

