/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Foundation/NSEnumerator.h>

@class NSMutableArray;

@interface MailboxUidChildrenEnumerator : NSEnumerator {
	NSMutableArray* _mailboxes;
	unsigned _index;
	BOOL _includeHidden;
}
// inherited: -(void)dealloc;
-(id)_initWithMailbox:(id)mailbox includeHiddenChildren:(BOOL)children;
// inherited: -(id)nextObject;
@end

