/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Foundation/NSURLProtocol.h>


@interface MessageURLProtocol : NSURLProtocol {
}
+(void)initialize;
// inherited: +(BOOL)canInitWithRequest:(id)request;
// inherited: +(id)canonicalRequestForRequest:(id)request;
// inherited: +(BOOL)requestIsCacheEquivalent:(id)equivalent toRequest:(id)request;
// inherited: -(void)startLoading;
// inherited: -(void)stopLoading;
@end

