/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Foundation/NSDictionary.h>


@interface NSDictionary (Goodies)
-(BOOL)boolForKey:(id)key;
-(int)integerForKey:(id)key;
@end

