/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Foundation/NSInvocation.h>


@interface NSInvocation (MailExtensions)
+(id)mf_invocationWithSelector:(SEL)selector target:(id)target;
+(id)mf_invocationWithSelector:(SEL)selector target:(id)target object:(id)object;
+(id)mf_invocationWithSelector:(SEL)selector target:(id)target object1:(id)a1 object2:(id)a2;
-(void)mf_invokeWithObject:(id)object;
-(BOOL)shouldLogInvocation;
@end

