/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <MIME/WRObject.h>

@class NSArray, PlainTextDocument, MailDelivery, MailAccount, DeliveryAccount, MutableMessageHeaders, NSString, Message;

@interface OutgoingMessageDelivery : WRObject {
	Message* _message;
	MutableMessageHeaders* _headers;
	NSArray* _mixedContent;
	BOOL _textPartsAreHTML;
	NSString* _htmlBody;
	PlainTextDocument* _plainTextAlternative;
	NSArray* _otherHTMLAndAttachments;
	id _delegate;
	MailAccount* _archiveAccount;
	DeliveryAccount* _deliveryAccount;
	MailDelivery* _currentDeliveryObject;
}
+(id)newWithMessage:(id)message;
+(id)newWithHeaders:(id)headers mixedContent:(id)content textPartsAreHTML:(BOOL)html;
+(id)newWithHeaders:(id)headers HTML:(id)html plainTextAlternative:(id)alternative other:(id)other;
// inherited: -(void)dealloc;
-(id)initWithMessage:(id)message;
-(id)initWithHeaders:(id)headers mixedContent:(id)content textPartsAreHTML:(BOOL)html;
-(id)initWithHeaders:(id)headers HTML:(id)html plainTextAlternative:(id)alternative other:(id)other;
-(id)_currentDeliveryObject;
-(id)originalHeaders;
-(int)_deliverSynchronouslyWithCurrentSettings:(BOOL)currentSettings;
-(int)deliverSynchronously;
-(int)deliveryStatus;
-(id)message;
-(id)_deliveryAccountForInitializers;
-(id)account;
-(void)setDelegate:(id)delegate;
-(void)setArchiveAccount:(id)account;
-(void)setAccount:(id)account;
@end

