/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "PlainTextDocument.h"
#import <Foundation/NSObject.h>

@class NSMutableArray, NSMutableString;

@interface PlainTextDocument : NSObject {
	NSMutableString* _text;
	NSMutableArray* _fragments;
}
// inherited: -(void)dealloc;
-(void)appendString:(id)string withQuoteLevel:(unsigned)quoteLevel;
-(unsigned)fragmentCount;
-(void)getString:(id*)string quoteLevel:(unsigned*)level ofFragmentAtIndex:(int)index;
-(id)string;
-(id)archivedRepresentation;
-(void)appendArchivedRepresentation:(id)representation;
@end

@interface PlainTextDocument (FormatFlowedSupport)
-(void)getFormatFlowedString:(id*)string insertedTrailingSpaces:(BOOL*)spaces encoding:(unsigned long)encoding;
@end

