/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Foundation/NSObject.h>


@interface POP3Fetcher : NSObject {
}
+(int)_fetchWithAccount:(id)account intoQueue:(id)queue newMessages:(unsigned)messages oldMessages:(unsigned)messages4 preservingUID:(id)uid withStore:(id)store;
+(int)fetchWithAccount:(id)account newMessages:(unsigned)messages oldMessages:(unsigned)messages3 preservingUID:(id)uid withStore:(id)store;
@end

