/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "MailAccount.h"

@class NSString, NSArray, ActivityMonitor, NSConditionLock, MFLock, POP3Connection;

@interface POPAccount : MailAccount {
	ActivityMonitor* _fetchMonitor;
	POP3Connection* _connection;
	NSConditionLock* _sharedConnectionCondition;
	unsigned _connectionsInUse;
	NSArray* _currentUIDs;
	MFLock* _connectionActivityLock;
	float _connectionTimeout;
	BOOL _fetcherNeedsReset;
	BOOL _deletingMessages;
	BOOL _hasDoneBackgroundSynchronization;
	BOOL _shouldAttemptAPOP;
	NSString* _oldestMessageUID;
	NSString* _newestMessageUID;
	int _numberOfKnownUIDs;
}
// inherited: +(id)accountTypeString;
// inherited: +(id)saslProfileName;
// inherited: -(id)init;
// inherited: -(void)dealloc;
// inherited: -(void)finalize;
// inherited: -(int)fetchSynchronously;
// inherited: -(int)fetchSynchronouslyLite;
-(int)fetchNumNewMessages:(unsigned)messages oldMessages:(unsigned)messages2 preservingUID:(id)uid withStore:(id)store;
// inherited: -(void)releaseAllConnections;
// inherited: -(void)releaseAllForcedConnections;
// inherited: -(BOOL)canGoOffline;
// inherited: -(void)setIsOffline:(BOOL)offline;
// inherited: -(unsigned)defaultPortNumber;
// inherited: -(unsigned)defaultSecurePortNumber;
// inherited: -(id)serviceName;
// inherited: -(id)secureServiceName;
// inherited: -(BOOL)requiresAuthentication;
// inherited: -(Class)storeClass;
// inherited: -(Class)storeClassForMailbox:(id)mailbox;
// inherited: -(Class)connectionClass;
// inherited: -(void)setPreferredAuthScheme:(id)scheme;
// inherited: -(id)mailboxPathExtension;
// inherited: -(BOOL)canCreateNewMailboxes;
// inherited: -(BOOL)canMailboxBeRenamed:(id)renamed;
-(int)bigMessageWarningSize;
-(void)setBigMessageWarningSize:(int)size;
-(BOOL)shouldAttemptAPOP;
-(void)setShouldAttemptAPOP:(BOOL)attemptAPOP;
-(void)setMessageDeletionPolicy:(int)policy;
-(void)setDelayedMessageDeletionInterval:(unsigned)interval;
-(int)messageDeletionPolicy;
-(unsigned)delayedMessageDeletionInterval;
-(BOOL)deletingMessages;
-(void)deleteMessagesNow:(id)now;
-(void)deleteSeenMessagesNow;
-(void)insertInMailboxes:(id)mailboxes atIndex:(unsigned)index;
-(void)acquireConnectionActivityLock;
-(void)relinquishConnectionActivityLock;
-(id)_URLScheme;
-(void)setOldestKnownMessageUID:(id)uid;
-(void)setNewestKnownMessageUID:(id)uid;
-(id)oldestKnownMessageUID;
-(id)newestKnownMessageUID;
-(void)setNumberOfKnownUIDs:(int)knownUIDs;
-(int)numberOfKnownUIDs;
// inherited: -(void)_deleteHook;
-(unsigned)connectionsInUse;
-(id)_getCachedConnection;
-(id)_createNewConnection;
// inherited: -(id)authenticatedConnection;
-(void)checkInConnection:(id)connection currentUIDs:(id)uids;
-(void)scheduleDisconnect;
-(void)closeConnection:(id)connection andSaveUIDs:(id)uids;
-(void)closeCachedConnectionForcedOnly:(id)only;
-(void)closeCachedConnection;
-(id)loginName;
-(BOOL)shouldRestoreMessagesAfterFailedDelete;
@end

