/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "DataConsumer.h"
#import <Foundation/NSObject.h>

@class NSMutableData;

@interface SimplePOPDataConsumer : NSObject <DataConsumer> {
	NSMutableData* _data;
}
// in a protocol: -(void)appendData:(id)data;
// in a protocol: -(void)done;
// in a protocol: -(id)data;
// inherited: -(void)dealloc;
@end

