/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "MailDelivery.h"


@interface SMTPDelivery : MailDelivery {
}
-(Class)deliveryClass;
// inherited: -(int)deliverMessageData:(id)data toRecipients:(id)recipients;
@end

