/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import <UIKit/UIViewController.h>
#import "MessageUI-Structs.h"

@class MailCompositionContext, MailComposeController;
@protocol MFMailComposeViewControllerDelegate;

@interface _MFMailComposeRootViewController : UIViewController {
	BOOL _isSuspended;
	MailCompositionContext* _compositionContext;
	MailComposeController* _mailComposeController;
	id<MFMailComposeViewControllerDelegate> _delegate;
	id _autorotationDelegate;
}
@property(assign, nonatomic) id<MFMailComposeViewControllerDelegate> delegate;
@property(assign, nonatomic) id autorotationDelegate;
-(id)initWithComposition:(id)composition;
// inherited: -(void)loadView;
// inherited: -(void)dealloc;
-(void)_presentPeoplePicker:(id)picker;
-(void)_dismissPeoplePicker:(id)picker;
-(id)_mailComposeController;
-(id)_compositionContext;
-(void)_setCompositionContext:(id)context;
-(id)_mailComposeView;
-(void)mailComposeControllerCompositionFinished:(id)finished;
-(void)_resume;
-(void)_suspend;
// inherited: -(void)viewWillAppear:(BOOL)view;
// inherited: -(void)viewDidDisappear:(BOOL)view;
// inherited: -(void)applicationWillSuspend;
// inherited: -(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
// inherited: -(id)rotatingHeaderView;
// inherited: -(id)rotatingFooterView;
// inherited: -(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
// inherited: -(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
// inherited: -(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
// inherited: -(void)_getRotationContentSettings:(XXStruct_TF$i3B*)settings;
@end

