/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import <Message/WebAttachmentSource.h>

@class NSMutableArray, NSMutableDictionary;

@interface GenericAttachmentStore : WebAttachmentSource {
	NSMutableDictionary* _attachmentsByURL;
	NSMutableArray* _attachmentsOrder;
	unsigned _size;
	unsigned _imagesSize;
	int _priority;
	BOOL _outgoing;
}
-(id)initOutgoing;
// inherited: -(void)dealloc;
-(BOOL)addAttachment:(id)attachment renamingContentID:(BOOL)anId;
-(void)removeAttachmentsForURLs:(id)urls;
// inherited: -(id)attachmentForURL:(id)url;
-(id)attachments;
-(void)setPriority:(int)priority;
-(int)priority;
@end

