/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import "MessageUI-Structs.h"
#import <UIKit/UIView.h>

@class NSString;

@interface HeaderLabelView : UIView {
	NSString* _label;
	unsigned _highlighted : 1;
}
-(CGColorRef)labelColor;
-(void)drawRect:(CGRect)rect;
-(void)setLabel:(id)label;
-(void)setLabelHighlighted:(BOOL)highlighted;
// inherited: -(void)dealloc;
@end

