/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import "MessageUI-Structs.h"
#import <UIKit/UIDefaultKeyboardInput.h>

@class MFAtomBackgroundView, UILabel;

@interface MFAtomView : UIDefaultKeyboardInput {
@private
	MFAtomBackgroundView* _background;
	UILabel* _label;
@protected
	id _delegate;
	unsigned _disclosure : 1;
	unsigned _needsCentering : 1;
	float _width;
}
+(id)backgroundImageWithDisclosure:(BOOL)disclosure selected:(BOOL)selected;
+(XXStruct_UUz0SD)backgroundImageSlicesWithDisclosure:(BOOL)disclosure;
+(float)defaultHeight;
+(float)horizontalPadding;
// inherited: -(id)initWithFrame:(CGRect)frame;
// inherited: -(void)dealloc;
-(id)title;
-(void)setTitle:(id)title;
-(float)preferredWidth;
-(void)setShowsDisclosure:(BOOL)disclosure;
-(BOOL)selected;
-(void)setSelected:(BOOL)selected;
-(void)showBackground:(BOOL)background;
-(void)layoutSubviews;
@end

