/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import <Foundation/NSArray.h>


@interface NSArray (RecipientListStrings)
-(id)commaSeparatedRecipientListWithWidth:(float)width forFont:(id)font;
-(id)commaSeparatedRecipientListWithWidth:(float)width forFont:(id)font usingSelector:(SEL)selector;
@end

