/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import <Foundation/NSSet.h>


@interface NSSet (MainThreadPerformAdditions)
-(void)makeObjectsPerformSelectorOnMainThread:(SEL)thread waitUntilDone:(BOOL)done;
-(void)makeObjectsPerformSelectorValue:(id)value;
@end

