/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import "MessageUI-Structs.h"
#import <UIKit/UIView.h>

@class UIImage;

@interface SearchShadowView : UIView {
	UIImage* _image;
}
+(id)_shadowImage;
+(float)defaultHeight;
// inherited: -(id)initWithFrame:(CGRect)frame;
// inherited: -(void)dealloc;
-(void)drawRect:(CGRect)rect;
@end

