/**
 * This header is generated by class-dump-z 0.1-11s.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

#import <Foundation/NSObject.h>

@class CPDistributedMessagingCenter;

/*!
 
 CPAggregateDictionary is an object to control a globally-shared dictionary. 
 Unless the Enabled key is set to "true" in ~/Library/com.apple.aggregated.plist, this class cannot be used. 
 
 */

@interface CPAggregateDictionary : NSObject {
	CPDistributedMessagingCenter* _center;
}
@property(readonly, assign, nonatomic, getter=isEnabled) BOOL enabled;
+(CPAggregateDictionary*)sharedAggregateDictionary;
// inherited: -(id)init;
// inherited: -(void)dealloc;
-(void)sendMessageName:(NSString*)name key:(NSString*)key arguments:(id)arguments;
-(void)sendMessageName:(NSString*)name key:(NSString*)key argument:(id)argument;
-(void)sendMessageName:(NSString*)name key:(NSString*)key;
-(void)clearKey:(id)key;
-(void)setValue:(int)value forScalarKey:(id)scalarKey;
-(void)incrementKey:(id)key;
-(void)decrementKey:(id)key;
-(void)addValue:(int)value forKey:(id)key;
-(void)subtractValue:(int)value forKey:(id)key;
-(void)setValue:(double)value forDistributionKey:(id)distributionKey;
-(void)pushValue:(double)value forKey:(id)key;
@end

