/**
 * This header is generated by class-dump-z 0.1-11s.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

#import <Foundation/NSObject.h>


@interface CPLRUDictionaryNode : NSObject {
	id _key;
	id _object;
	CPLRUDictionaryNode* next;
	CPLRUDictionaryNode* prev;
}
@property(readonly, assign, nonatomic) id key;
@property(retain, nonatomic) id object;
-(id)initWithKey:(id)key object:(id)object;
// inherited: -(void)dealloc;
@end

