/**
 * This header is generated by class-dump-z 0.1-11s.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

#import "CPLRUDictionary.h"
#import <Foundation/NSObject.h>

@class CPLRUDictionaryNode, NSMutableDictionary;

@interface CPLRUDictionary : NSObject {
	NSMutableDictionary* _dictionary;
	unsigned _maxCount;
	CPLRUDictionaryNode* _head;
	CPLRUDictionaryNode* _tail;
}
-(id)initWithMaximumCapacity:(unsigned)maximumCapacity;
-(unsigned)count;
-(id)allKeys;
-(id)objectForKey:(id)key;
-(void)setObject:(id)object forKey:(id)key;
-(void)removeObjectForKey:(id)key;
-(void)removeAllObjects;
@end

@interface CPLRUDictionary (NodeHelpers)
-(void)_removeNodeFromLinkedList:(id)linkedList;
-(void)_removeNode:(id)node;
-(void)_moveNodeToFront:(id)front;
-(void)_addNodeToFront:(id)front;
@end

