/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

#import "AVQueueFeeder.h"

@class NSMutableArray;

@interface AVArrayQueueFeeder : AVQueueFeeder {
@private
	NSMutableArray* _items;
}
-(id)init;
-(id)initWithArray:(id)array;
-(void)dealloc;
-(id)itemForIndex:(unsigned)index;
-(unsigned)itemCount;
-(unsigned)numberOfPaths;
-(id)pathAtIndex:(unsigned)index;
-(void)insertObject:(id)object atIndex:(unsigned)index;
-(void)removeObjectAtIndex:(unsigned)index;
-(void)shuffleWithCurrentIndex:(unsigned)currentIndex;
@end

