/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface AVSafePerformOnMainThreadTargetDict : NSObject {
	NSMutableDictionary* _obj;
}
+(id)dict;
-(id)init;
-(void)dealloc;
-(void)release;
-(void)setObject:(id)object forKey:(id)key;
-(id)objectForKey:(id)key;
@end

