/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "ASItem.h"
#import "ASParsingAcceptingTopLevelLeaves.h"

@class NSMutableDictionary, NSString;

@interface ASAttendee : ASItem <ASParsingAcceptingTopLevelLeaves> {
	NSString* _name;
	NSString* _email;
	int _status;
	int _role;
	int _localId;
	NSMutableDictionary* _placeHolder;
}
@property(retain) NSString* name;
@property(retain) NSString* email;
@property(assign) int status;
@property(assign) int role;
@property(assign) int localId;
// inherited: +(BOOL)acceptsTopLevelLeaves;
// inherited: +(BOOL)parsingLeafNode;
// inherited: +(BOOL)parsingWithSubItems;
// inherited: +(BOOL)frontingBasicTypes;
// in a protocol: -(void)applyPlaceHolder;
// in a protocol: -(void)clearPlaceHolder;
// in a protocol: -(void)setObject:(id)object forCCPT:(int)ccpt;
// inherited: -(id)asParseRules;
-(void)saveToCalendarWithParentASEvent:(id)parentASEvent existingRecord:(void*)record treatNullsAsDeletes:(BOOL)deletes;
-(id)initWithCalAttendee:(void*)calAttendee parentEvent:(id)event;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)appendActiveSyncDataForTask:(id)task toData:(id)data;
-(id)fullEmailString;
// inherited: -(void)dealloc;
-(id)copyOfSelfWithoutLocalID;
-(id)icsUserAddress;
@end

