/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */



@protocol ASDataElement
-(BOOL)saveWithLocalObject:(void*)localObject toContainer:(void*)container treatNullsAsDeletes:(BOOL)deletes account:(id)account;
-(BOOL)saveAfterMapWithLocalObject:(void*)localObject toContainer:(void*)container treatNullsAsDeletes:(BOOL)deletes account:(id)account;
-(BOOL)hasLocalModificationsWithLocalObject:(void*)localObject;
-(void)setLocalItem:(void*)item;
-(BOOL)loadLocalItemWithAccount:(id)account;
-(BOOL)saveServerIDToExistingItem;
-(BOOL)deleteFromContainer:(void*)container;
@end

