/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "ASEventChangeCommand.h"

@class ASEvent;

@interface ASEventPseudoDeleteCommand : ASEventChangeCommand {
	ASEvent* _actualEvent;
}
// inherited: -(id)initWithEvent:(id)event;
// inherited: -(void)appendApplicationDataForTask:(id)task toWBXMLData:(id)wbxmldata;
@end

