/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "ASSearchTask.h"


@interface ASMailboxSearchTask : ASSearchTask {
}
// inherited: -(BOOL)requiresEASVersionInformaton;
// inherited: -(void)performTask;
-(void)_appendSearchQuery:(id)query;
-(void)_appendSearchOptions:(id)options;
// inherited: -(id)requestBody;
-(id)replacementObjectForEmailItem:(id)emailItem;
// inherited: -(BOOL)processContext:(id)context;
// inherited: -(void)finishWithError:(id)error;
@end

