/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "DAMailMessage.h"

@class ASEmailItem;

@interface ASMailMessage : DAMailMessage {
	ASEmailItem* _ASEmailItem;
}
// inherited: -(void)dealloc;
-(id)initWithASEmailItem:(id)asemailItem;
// inherited: -(id)description;
// inherited: -(id)to;
// inherited: -(id)cc;
// inherited: -(id)from;
// inherited: -(id)replyTo;
// inherited: -(id)date;
// inherited: -(id)subject;
// inherited: -(id)displayTo;
// inherited: -(int)importance;
// inherited: -(BOOL)read;
// inherited: -(id)body;
// inherited: -(int)bodySize;
// inherited: -(int)bodyTruncated;
// inherited: -(id)messageClass;
// inherited: -(id)attachments;
// inherited: -(id)meetingRequestUUID;
// inherited: -(id)meetingRequestMetaData;
// inherited: -(id)threadTopic;
// inherited: -(id)remoteID;
// inherited: -(id)longID;
// inherited: -(id)rfc822Data;
@end

