/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "ASTask.h"

@class NSMutableArray;

@interface ASMoveItemsTask : ASTask {
	NSMutableArray* _moveItems;
}
// inherited: -(void)dealloc;
// inherited: -(int)commandCode;
-(void)addSourceID:(id)anId sourceFolder:(id)folder destinatonFolder:(id)folder3;
// inherited: -(BOOL)processContext:(id)context;
// inherited: -(void)finishWithError:(id)error;
// inherited: -(id)requestBody;
// inherited: -(int)taskStatusForExchangeStatus:(int)exchangeStatus;
@end

