/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "ASTask.h"

@class NSSet;

@interface ASPingTask : ASTask {
	NSSet* _folders;
	NSSet* _oldFolders;
	int _seconds;
	int _oldSeconds;
}
-(id)initWithHeartbeat:(int)heartbeat folders:(id)folders oldHeartbeat:(int)heartbeat3 oldFolders:(id)folders4;
// inherited: -(void)dealloc;
// inherited: -(BOOL)forceEDGETransport;
// inherited: -(BOOL)shouldHoldPowerAssertion;
// inherited: -(int)commandCode;
-(int)heartbeat;
-(id)folders;
// inherited: -(double)timeoutInterval;
// inherited: -(id)requestBody;
// inherited: -(BOOL)processContext:(id)context;
-(void)requestCancelTaskWithReason:(int)reason;
// inherited: -(void)finishWithError:(id)error;
// inherited: -(int)taskStatusForExchangeStatus:(int)exchangeStatus;
@end

