/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "ASItem.h"

@class NSArray, NSNumber;

@interface ASPingItem : ASItem {
	NSArray* _folders;
	NSNumber* _heartBeatInterval;
	NSNumber* _maxFolders;
	NSNumber* _status;
}
// inherited: +(BOOL)acceptsTopLevelLeaves;
// inherited: +(BOOL)parsingLeafNode;
// inherited: +(BOOL)parsingWithSubItems;
// inherited: +(BOOL)frontingBasicTypes;
// inherited: -(id)asParseRules;
// inherited: -(void)dealloc;
// inherited: -(id)description;
-(void)setFolders:(id)folders;
-(id)folders;
-(id)heartBeatInterval;
-(void)setHeartBeatInterval:(id)interval;
-(id)maxFolders;
-(void)setMaxFolders:(id)folders;
-(id)status;
-(void)setStatus:(id)status;
@end

