/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import <DAVKit/AYOperation.h>

@class DAVSession, NSString;

@interface CalDAVUpdateCalendarFreeBusyOperation : AYOperation {
	NSString* _fromURI;
	NSString* _toURI;
	NSString* _inboxURI;
	DAVSession* _session;
}
-(id)initWithSession:(id)session fromURI:(id)uri toURI:(id)uri3 inboxURI:(id)uri4;
// inherited: -(void)dealloc;
-(void)updateFreeBusySet;
@end

