/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import <Foundation/NSObject.h>
#import "CalDAVCacheManager.h"

@class NSMutableSet, MobileCalDAVCalendar, NSMutableDictionary;

@interface CalDAVCacheManager : NSObject {
	MobileCalDAVCalendar* _calendar;
	NSMutableDictionary* _filenameToModifiedLocallyMap;
	NSMutableSet* _locallyDeletedFilenames;
	NSMutableDictionary* _externalIDToLocalUIDMap;
}
+(id)cacheControllerForCalendar:(id)calendar;
+(void)clearAllCacheControllers;
// inherited: -(id)init;
// inherited: -(void)dealloc;
-(void)setETag:(id)tag forFilename:(id)filename;
-(void)setETag:(id)tag forEventWithExternalID:(id)externalID;
-(id)etagForFilename:(id)filename;
-(id)filenameForUID:(id)uid;
-(void)setFilename:(id)filename forUID:(id)uid;
-(id)uidForFilename:(id)filename;
-(void)setLocallyModified:(BOOL)modified forFilename:(id)filename;
-(void)setFilenameLocallyDeleted:(id)deleted;
-(void)setUIDModified:(id)modified;
-(BOOL)isFileLocallyModified:(id)modified;
-(void)setEventModified:(id)modified;
-(void)setExternalID:(id)anId forLocalUID:(int)localUID;
-(int)localUIDForExternalID:(id)externalID;
-(void)endChanges;
-(id)allFilenames;
@end

@interface CalDAVCacheManager (Private)
-(id)_initWithCalendar:(id)calendar;
@end

