/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface CDLRProperty : NSObject {
	int type;
	NSString* value;
	int statusCode;
}
@property(assign, nonatomic) int type;
@property(retain, nonatomic) NSString* value;
@property(assign, nonatomic) int statusCode;
-(id)initWithType:(int)type value:(id)value statusCode:(int)code;
// inherited: -(void)dealloc;
@end

