/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "DACalendarObject.h"

@class NSArray, DACalendarStore, NSString;

@interface DACalendar : DACalendarObject {
}
@property(readonly, assign, nonatomic) NSArray* events;
@property(retain, nonatomic) NSString* color;
@property(retain, nonatomic) NSString* title;
@property(readonly, assign, nonatomic) DACalendarStore* store;
@property(readonly, assign, nonatomic) NSString* externalID;
@property(readonly, assign, nonatomic) int uid;
// inherited: -(BOOL)isEqual:(id)equal;
-(void)addEvent:(id)event;
-(void)removeAllEvents;
-(void)remove;
@end

