/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import <Foundation/NSObject.h>


@interface DAMailMessage : NSObject {
}
-(id)to;
-(id)cc;
-(id)from;
-(id)replyTo;
-(id)date;
-(id)subject;
-(id)displayTo;
-(int)importance;
-(BOOL)read;
-(id)body;
-(int)bodySize;
-(int)bodyTruncated;
-(id)messageClass;
-(id)attachments;
-(id)meetingRequestUUID;
-(id)meetingRequestMetaData;
-(id)threadTopic;
-(id)remoteID;
-(id)longID;
-(id)rfc822Data;
@end

