/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "NSObject.h"


@protocol DATask <NSObject>
-(void)performTask;
-(void)cancelTaskWithReason:(int)reason underlyingError:(id)error;
@optional
-(void)startModal;
-(void)requestCancelTaskWithReason:(int)reason;
-(BOOL)shouldHoldPowerAssertion;
-(id)powerAssertionGroupIdentifier;
-(void)setTaskManager:(id)manager;
@end

