/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import <Foundation/NSObject.h>
#import "DAAccountActorMessages.h"


@interface LDAPAccountActorZombie : NSObject <DAAccountActorMessages> {
}
+(id)sharedZombie;
// in a protocol: -(oneway void)cancelTaskWithID:(int)anId;
-(void)performSearchQuery:(id)query consumer:(id)consumer;
-(void)cancelSearchQuery:(id)query;
-(void)cancelAllSearchQueries;
// in a protocol: -(BOOL)searchQueriesRunning;
// in a protocol: -(oneway void)startup;
// in a protocol: -(oneway void)setAccount:(id)account;
// in a protocol: -(oneway void)shutdown;
@end

