/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import <Foundation/NSArray.h>


@interface NSArray (CALExtensions)
+(id)convertFromXML:(id)xml;
-(id)allObjectsWithClass:(Class)aClass;
-(id)descriptionByPointer;
-(id)convertToXML;
-(id)deepCopy;
// inherited: -(BOOL)containsObjectIdenticalTo:(id)to;
-(unsigned)indexOfObject:(id)object matchingComparison:(SEL)comparison;
-(BOOL)containsObject:(id)object matchingComparison:(SEL)comparison;
@end

