/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "DAAccount.h"
#import "DataAccess-Structs.h"

@class DATaskManager, NSDictionary, NSMutableDictionary, NSURL, NSString, NSData;

@interface SubCalAccount : DAAccount {
	DATaskManager* _taskManager;
	NSMutableDictionary* _consumers;
	NSData* _tmpICSData;
}
@property(retain, nonatomic) NSMutableDictionary* consumers;
@property(assign) int subCalAccountVersion;
@property(readonly, retain, nonatomic) NSURL* subscriptionURL;
@property(readonly, retain, nonatomic) NSString* scheduleIdentifier;
@property(retain, nonatomic) NSDictionary* externalRepresentation;
@property(retain, nonatomic) NSString* syncId;
@property(assign) BOOL shouldRemoveAlarms;
// inherited: +(Class)accountClass;
// inherited: +(Class)clientClass;
// inherited: +(id)defaultProperties;
+(id)supportedDataclasses;
// inherited: -(void)dealloc;
// inherited: -(BOOL)supportsAccountType:(int)type;
-(id)taskManager;
-(void)setConsumer:(id)consumer forTask:(id)task;
-(id)consumerForTask:(id)task;
-(void)removeConsumerForTask:(id)task;
-(void)_checkValidityWithConsumer:(id)consumer quickValidate:(BOOL)validate;
// inherited: -(void)checkValidityWithConsumer:(id)consumer;
-(void)quickValidate:(id)validate;
-(void)subCalValidationTask:(id)task finishedWithError:(id)error calendarName:(id)name calendarData:(id)data;
-(id)_tmpICSCalendarPath;
-(void)setTmpICSData:(id)data;
-(void)saveTmpICSData;
-(id)tmpICSData;
-(void)clearTmpICSData;
-(BOOL)_upgradeSelfFromVersion:(int)version superClassUpgraded:(BOOL)upgraded accountManager:(id)manager;
// inherited: -(BOOL)upgradeAccountIfNecessaryWithAccountManager:(id)accountManager;
// inherited: -(id)urlForKeychain;
// inherited: -(id)username;
// inherited: -(void)setUsername:(id)username;
// inherited: -(id)host;
// inherited: -(void)setHost:(id)host;
// inherited: -(int)port;
// inherited: -(void)setPort:(int)port;
// inherited: -(BOOL)useSSL;
// inherited: -(void)setUseSSL:(BOOL)ssl;
-(void)refreshAllCalendars;
-(BOOL)subCalDATask:(id)task shouldAllowTrust:(SecTrust*)trust forHost:(id)host;
@end

