/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import <Foundation/NSObject.h>

@class NSMutableData;

@interface WBXMLData : NSObject {
@private
	NSMutableData* _data;
	unsigned char _currentCodePage;
	BOOL _haveAppliedCurrentCodePage;
	NSMutableData* _stateStack;
}
@property(readonly, assign, nonatomic) NSMutableData* data;
-(void)_applyCurrentCodePage;
-(void)appendString:(id)string;
-(void)appendInt:(int)anInt;
-(void)renderProspectiveTags;
-(unsigned char)currentCodePage;
-(void)switchToCodePage:(unsigned char)codePage;
-(void)openProspectiveTag:(unsigned char)tag;
-(void)closeProspectiveTag:(unsigned char)tag;
-(void)appendEmptyTag:(unsigned char)tag;
-(void)openTag:(unsigned char)tag;
-(void)closeTag:(unsigned char)tag;
-(void)appendTag:(unsigned char)tag withStringContent:(id)stringContent;
-(void)appendTag:(unsigned char)tag withIntContent:(int)intContent;
// inherited: -(void)dealloc;
// inherited: -(id)init;
@end

