/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIThreePartButton.h"
#import "UIKit-Structs.h"

@class UILabel;

@interface _UILabeledPushButton : UIThreePartButton {
	UILabel* _textLabel;
}
-(void)dealloc;
-(void)setLabel:(id)label;
-(void)setLabelFontSize:(float)size;
-(float)labelFontSize;
-(void)layoutSubviews;
-(void)setHighlighted:(BOOL)highlighted;
-(void)drawTitleAtPoint:(CGPoint)point width:(float)width;
@end

