/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class UIView, UIControl, UIRemoveControl;

@interface _UITableViewCellOldEditingData : NSObject {
	UIRemoveControl* _removeControl;
	UIControl* _grabber;
	UIView* _separator;
}
@property(retain, nonatomic) UIControl* reorderControl;
@property(retain, nonatomic) UIView* separatorView;
-(BOOL)dataRequired;
-(void)dealloc;
@end

