/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class UIView, UIControl, UIRemoveControl;

@interface _UITableCellTransientData : NSObject {
	UIRemoveControl* _removeControl;
	UIControl* _grabber;
	UIView* _separator;
	unsigned _reorderingEnabled : 1;
	unsigned _hidSeparatorForRemoveConfirmation : 1;
	unsigned _reserved : 30;
}
-(BOOL)dataRequired;
@end

