/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIView.h>

@class UITableView, UITableViewCell;

@interface _UITableViewSeparatorView : UIView {
	UITableViewCell* _tableCell;
	UITableView* _table;
}
-(id)initWithTableCell:(id)tableCell;
-(id)initWithFrame:(CGRect)frame withTable:(id)table;
-(void)drawRect:(CGRect)rect;
@end

