/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>


@interface ABHelper : NSObject {
	void* _ab;
	void* _me;
}
+(id)sharedHelper;
-(id)initHelper;
-(void)dealloc;
-(void*)me;
@end

