/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSString, NSData;

@interface CandWordString : NSObject {
	NSString* _string;
	char* _UTF8String;
	NSData* _utf8Data;
}
-(id)initWithString:(id)string;
-(void)dealloc;
-(id)string;
-(const char*)UTF8String;
@end

