/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIScrollView.h>


@interface EmojiScrollView : UIScrollView {
	double _delay;
	BOOL _canDragToScroll;
}
@property(assign) double delay;
-(id)initWithFrame:(CGRect)frame;
-(double)_touchDelayForScrollDetection;
-(void)setContentOffset:(CGPoint)offset;
-(void)_stopLookingForScrolling;
-(void)_lookForScrolling;
-(BOOL)touchesShouldBegin:(id)touches withEvent:(id)event inContentView:(id)contentView;
-(BOOL)touchesShouldCancelInContentView:(id)touches;
@end

