/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIPageControl.h>


@interface EmojiPageControl : UIPageControl {
}
-(id)_pageIndicatorImageForPage:(int)page;
-(id)_pageIndicatorCurrentImageForPage:(int)page;
-(void)_setCurrentPage:(int)page;
@end

