/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSArray;

@interface FormToABBinder : NSObject {
	NSDictionary* _abPointers;
	NSArray* _fieldLabels;
	NSDictionary* _synonyms;
}
+(void)loadBinders;
+(void)clearBinders;
+(id)abPointerForControl:(id)control rep:(id)rep useFieldName:(BOOL)name;
+(id)synonymsForMatch:(id)match;
-(void)_indexMapping:(id)mapping;
-(id)initWithPath:(id)path;
-(void)dealloc;
-(id)abPointerForControl:(id)control rep:(id)rep useFieldName:(BOOL)name foundByPageScan:(BOOL*)scan;
-(id)synonymsForMatch:(id)match;
@end

