/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIView.h>

@class NSString;

@interface KBCandidateCell : UIView {
	NSString* _candidate;
	unsigned _index;
	CGSize _stringImageSize;
	BOOL _isLastInLine;
	BOOL _highlighted;
	float _atBottom;
	id _target;
	SEL _action;
	BOOL _drawDone;
	BOOL _stringMayBeTooLong;
}
+(id)font;
-(id)initWithCandidate:(id)candidate andIndex:(unsigned)index target:(id)target action:(SEL)action;
-(void)dealloc;
-(CGSize)stringImageSize;
-(unsigned)index;
-(void)setGap:(float)gap;
-(float)dividorOriginX;
-(void)setLastInLine:(BOOL)line;
-(void)setStringMayBeTooLong:(BOOL)aLong;
-(void)setAtBottom:(BOOL)bottom;
-(void)drawRect:(CGRect)rect;
-(void)setHighlighted:(BOOL)highlighted;
-(void)selected;
-(void)mouseUp:(GSEventRef)up;
-(void)touchesEnded:(id)ended withEvent:(id)event;
@end

