/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSArray.h>
#import "UIKit-Structs.h"


@interface NSMutableArray (UICollectionAdditions_Performance)
-(void)addObjectsFromArray:(id)array range:(NSRange)range;
@end

@interface NSMutableArray (UICollectionAdditions)
-(void)push:(void*)push;
-(void*)pop;
@end

@interface NSMutableArray (UIKBExtras)
-(void)_kb_reverse;
@end

@interface NSMutableArray (UIMovieScrubberTrackViewAdditions)
-(void)removeViewsFromSuperview;
@end

