/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIBarButtonItem.h>
#import <UIKit/UIBarItem.h>
#import <Availability2.h>

@class NSString, UIToolbarButton, UIImage, NSSet, UIView;

@interface UIBarButtonItem ()
-(id)init;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)setEnabled:(BOOL)enabled;
-(BOOL)isEnabled;
-(void)setTitle:(id)title;
-(id)title;
-(void)setImage:(id)image;
-(id)image;
-(void)setImageInsets:(UIEdgeInsets)insets;
-(UIEdgeInsets)imageInsets;
@end

@interface UIBarButtonItem (SynthEvents)
-(id)scriptingID;
@end

@interface UIBarButtonItem (Static)
+(Class)classForNavigationButton;
-(void)_getSystemItemStyle:(int*)style title:(id*)title image:(id*)image selectedImage:(id*)image4 action:(SEL*)action forBarStyle:(int)barStyle landscape:(BOOL)landscape alwaysBordered:(BOOL)bordered;
-(void)_getNavBarEdgeSizeAdjust:(CGSize*)adjust imageInsets:(UIEdgeInsets*)insets landscape:(BOOL)landscape;
-(void)_getToolbarEdgeInsets:(UIEdgeInsets*)insets imageInsets:(UIEdgeInsets*)insets2 glowInsets:(UIEdgeInsets*)insets3 forBarStyle:(int)barStyle landscape:(BOOL)landscape alwaysBordered:(BOOL)bordered;
#if __IPHONE_OS_VERSION_MAX_ALLOWED < __IPHONE_3_2
-(id)createViewForNavigationItem:(id)navigationItem;
-(id)createViewForToolbar:(id)toolbar;
#endif
-(void)_updateView;
@end

@interface UIBarButtonItem (Internal)
@property(readonly, assign, nonatomic) int systemItem;
@property(readonly, assign, nonatomic) BOOL isSystemItem;
@property(readonly, assign, nonatomic) BOOL isCustomViewItem;
@property(retain, nonatomic) UIView* view;
-(id)nextResponder;
-(BOOL)isMinibarView;
-(void)setIsMinibarView:(BOOL)view;
-(void)_sendAction:(id)action withEvent:(id)event;
@end

@interface UIBarButtonItem (UIBarButtonItemPrivate)
@property(readonly, assign, nonatomic) UIToolbarButton* _toolbarButton;
@property(assign, nonatomic, getter=isEnabled) BOOL enabled;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
@property(assign, nonatomic) BOOL _shouldBezelImage;
-(id)createViewForNavigationItem:(id)navigationItem;
-(id)createViewForToolbar:(id)toolbar;
-(void)_setWidth:(float)width;
-(float)_width;
#endif
@end

