/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "NSCoding.h"
#import "UIKit-Structs.h"
#import <UIKit/UIButton.h>
#import <UIKit/UIControl.h>
#import <Availability2.h>

@class UILabel, UIImage, UIImageView, NSString, UIColor, UIFont;

@interface UIButton ()
+(id)_defaultContentForType:(int)type andState:(unsigned)state;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(void)_populateArchivedSubviews:(id)subviews;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(void)setBounds:(CGRect)bounds;
-(void)setSelected:(BOOL)selected;
-(void)setEnabled:(BOOL)enabled;
-(void)setHighlighted:(BOOL)highlighted;
-(void)setContentHorizontalAlignment:(int)alignment;
-(CGRect)backgroundRectForBounds:(CGRect)bounds;
-(CGRect)contentRectForBounds:(CGRect)bounds;
-(CGRect)titleRectForContentRect:(CGRect)contentRect;
-(CGRect)imageRectForContentRect:(CGRect)contentRect;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
@end

@interface UIButton (SyntheticEvents)
-(id)_scriptingInfo;
@end

@interface UIButton (UIButtonContentLookup)
-(void)_setContent:(id)content forState:(unsigned)state;
-(void)_setImage:(id)image forStates:(unsigned)states;
-(void)_setBackground:(id)background forStates:(unsigned)states;
-(void)_setTitle:(id)title forStates:(unsigned)states;
-(void)_setTitleColor:(id)color forStates:(unsigned)states;
-(void)_setShadowColor:(id)color forStates:(unsigned)states;
-(id)_contentForState:(unsigned)state;
-(id)_archivableContent:(id*)content;
-(void)_takeContentFromArchivableContent:(id)archivableContent overrides:(id)overrides;
-(id)_imageForState:(unsigned)state usesImageForNormalState:(BOOL*)normalState;
-(id)_backgroundForState:(unsigned)state usesBackgroundForNormalState:(BOOL*)normalState;
-(id)_titleForState:(unsigned)state;
-(id)_titleColorForState:(unsigned)state;
-(id)_shadowColorForState:(unsigned)state;
@end

@interface UIButton (UIButtonPrivate)
@property(retain, nonatomic) UIColor* tintColor;
-(BOOL)_alwaysHandleScrollerMouseEvent;
-(void)_setShouldHandleScrollerMouseEvent:(BOOL)_set;
-(void)setAutosizesToFit:(BOOL)fit;
-(BOOL)autosizesToFit;
-(void)setDisabledDimsImage:(BOOL)image;
-(void)setShowPressFeedback:(BOOL)feedback;
-(CGPoint)pressFeedbackPosition;
-(void)setTitle:(id)title forStates:(unsigned)states;
-(void)setTitleColor:(id)color forStates:(unsigned)states;
-(void)setTitleShadowColor:(id)color forStates:(unsigned)states;
-(void)setImage:(id)image forStates:(unsigned)states;
-(void)setBackgroundImage:(id)image forStates:(unsigned)states;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
-(void)crossfadeAnimationDidStop:(id)crossfadeAnimation finished:(id)finished context:(void*)context;
-(void)crossfadeToImage:(id)image forState:(unsigned)state;
#endif
-(id)_font;
-(void)_setFont:(id)font;
-(int)_lineBreakMode;
-(void)_setLineBreakMode:(int)mode;
-(CGSize)_titleShadowOffset;
-(void)_setTitleShadowOffset:(CGSize)offset;
@end

@interface UIButton (UIButtonInternal)
-(void)_setupBackgroundView;
-(void)_setupImageView;
-(void)_setupTitleView;
-(void)_setButtonType:(int)type;
-(void)_titleAttributesChanged;
@end

@interface UIButton (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isAccessibilityElementByDefault;
-(unsigned long long)defaultAccessibilityTraits;
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

