/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "UIDeviceWhiteColor.h"


@interface UICachedDeviceWhiteColor : UIDeviceWhiteColor {
}
-(void)release;
-(id)retain;
-(unsigned)retainCount;
-(id)autorelease;
-(id)copyWithZone:(NSZone*)zone;
-(id)copy;
-(void)dealloc;
-(void)finalize;
@end

