/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIButton.h>
#import <Availability2.h>

@class NSTimer;

@interface UICalloutBarButton : UIButton {
	SEL m_action;
	int m_position;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	int m_type;
#endif
	NSTimer* m_flashTimer;
	float m_contentWidth;
	float m_contentScale;
	int m_flashCount;
	BOOL m_isText;
	BOOL m_configured;
	BOOL m_single;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
	BOOL m_padLeft;
	BOOL m_padRight;
#endif
}
@property(readonly, assign, nonatomic) SEL action;
@property(readonly, assign, nonatomic) float contentWidth;
@property(readonly, assign, nonatomic) float contentScale;
// inherited: -(void)dealloc;
-(void)configureLabel;
// inherited: -(void)layoutSubviews;
-(void)removeFromSuperview;
// inherited: -(CGRect)titleRectForContentRect:(CGRect)contentRect;
// inherited: -(CGRect)imageRectForContentRect:(CGRect)contentRect;
-(void)configureForMiddlePosition;
-(void)setContentScale:(float)scale;
// inherited: -(void)setHighlighted:(BOOL)highlighted;
-(void)sendCallback;
-(void)cancelFlash;
-(void)flash;
-(void)flashCallback:(id)callback;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
@property(readonly, assign, nonatomic) int type;
+(id)buttonWithTitle:(id)title action:(SEL)action type:(int)type inView:(id)view;
+(id)buttonWithImage:(id)image action:(SEL)action type:(int)type inView:(id)view;
-(void)_commonSetupWithAction:(SEL)action type:(int)type;
-(void)setupWithTitle:(id)title action:(SEL)action type:(int)type;
-(void)setupWithImage:(id)image action:(SEL)action type:(int)type;
-(void)configureForSingle:(int)single;
-(void)configureForLeftPosition:(int)leftPosition;
-(void)configureForRightPosition:(int)rightPosition;
#else
+(id)buttonWithTitle:(id)title action:(SEL)action inView:(id)view;
+(id)buttonWithImage:(id)image action:(SEL)action inView:(id)view;
-(void)setupWithTitle:(id)title action:(SEL)action;
-(void)setupWithImage:(id)image action:(SEL)action;
-(void)configureForSingle;
-(void)configureForLeftPosition;
-(void)configureForRightPosition;
#endif
@end

