/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIView.h>

@class NSArray, NSMutableArray, UICalloutBarOverlay;

@interface UICalloutBar : UIView {
	id m_delegate;
	CGPoint m_pointBelowControls;
	CGPoint m_pointAboveControls;
	BOOL m_pointPositionedBelowControls;
	BOOL m_fadeAfterCommand;
	BOOL m_updateVisibleItems;
	CGRect m_controlFrame;
	CGRect m_targetRect;
	NSMutableArray* m_buttons;
	NSMutableArray* m_rectsToEvade;
	UICalloutBarOverlay* m_overlay;
	double m_fadedTime;
}
@property(assign, nonatomic) CGPoint pointAboveControls;
@property(assign, nonatomic) CGPoint pointBelowControls;
@property(assign, nonatomic) BOOL pointPositionedBelowControls;
@property(assign, nonatomic) CGRect controlFrame;
@property(assign, nonatomic) id delegate;
@property(readonly, assign, nonatomic) NSArray* rectsToEvade;
@property(assign, nonatomic) CGRect targetRect;
@property(readonly, assign, nonatomic) BOOL visible;
+(id)sharedCalloutBar;
+(BOOL)sharedCalloutBarIsVisible;
+(void)fadeSharedCalloutBar;
+(void)hideSharedCalloutBar;
+(BOOL)sharedCalloutBarWasRecentlyFaded;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(id)targetForAction:(SEL)action;
-(void)buttonPressed:(id)pressed;
-(void)removeFromSuperview;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(int)textEffectsVisibilityLevel;
-(BOOL)rectClear:(CGRect)clear;
-(BOOL)calculateControlFrameForPointBelowControls:(float)pointBelowControls;
-(BOOL)calculateControlFrameForPointAboveControls:(float)pointAboveControls;
-(BOOL)calculateControlFrameInsideTargetRect:(float)rect;
-(id)visibleButtons;
-(BOOL)positionIsValid;
-(BOOL)updateVisibleItems;
-(void)setTargetRect:(CGRect)rect pointBelowControls:(CGPoint)controls pointAboveControls:(CGPoint)controls3;
-(void)buttonHighlighted:(id)highlighted highlighted:(BOOL)highlighted2;
-(void)appear;
-(void)fade;
-(void)hide;
-(BOOL)recentlyFaded;
-(void)appearAnimationDidStop:(id)appearAnimation finished:(id)finished;
-(void)zoomDownAnimationDidStop:(id)zoomDownAnimation finished:(id)finished;
-(void)addRectToEvade:(CGRect)evade;
-(void)clearEvadeRects;
@end

@protocol UICalloutBarDelegate
@optional
-(void)calloutBarWillStartAnimation:(UICalloutBar*)calloutBar;
-(void)calloutBarDidFinishAnimation:(UICalloutBar*)calloutBar;
@end

