/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIColor.h>

__attribute__((visibility("hidden")))
@interface UICGColor : UIColor {
@private
	CGColorRef cachedColor;
}
// inherited: -(id)initWithCGColor:(CGColorRef)cgcolor;
// inherited: -(void)dealloc;
// inherited: -(id)colorWithAlphaComponent:(float)alphaComponent;
// inherited: -(void)set;
// inherited: -(void)setFill;
// inherited: -(void)setStroke;
-(id)colorSpaceName;
// inherited: -(id)description;
// inherited: -(BOOL)isEqual:(id)equal;
// inherited: -(unsigned)hash;
// inherited: -(CGColorRef)CGColor;
// inherited: -(float)alphaComponent;
@end

