/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIView.h>
#import <Availability2.h>

@class UIImageView;

#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
__attribute__((visibility("hidden")))
#endif
@interface UIClippedImageView : UIView {
	UIImageView* m_imageView;
	CGRect m_originalFrame;
	CGRect m_baseFrame;
}
-(id)initWithFrame:(CGRect)frame image:(id)image;
-(void)dealloc;
-(id)image;
-(void)setImage:(id)image;
-(void)setOpaque:(BOOL)opaque;
-(void)setFrame:(CGRect)frame;
-(void)setBaseFrame:(CGRect)frame;
-(CGRect)baseFrame;
-(void)setImageOrigin:(CGPoint)origin;
-(void)setOriginAdjustingImage:(CGPoint)image;
@end

