/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <Foundation/NSObject.h>
#import <Availability2.h>

@class UIImage;

#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
__attribute__((visibility("hidden")))
#endif
@interface UICompositeImageElement : NSObject {
	UIImage* m_image;
	CGRect m_fromRect;
	CGRect m_toRect;
	int m_operation;
	float m_fraction;
}
+(id)elementWithImage:(id)image toRect:(CGRect)rect fromRect:(CGRect)rect3 operation:(int)operation fraction:(float)fraction;
-(id)initWithImage:(id)image toRect:(CGRect)rect fromRect:(CGRect)rect3 operation:(int)operation fraction:(float)fraction;
-(void)dealloc;
-(void)draw;
@end

