/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UILabel.h>
#import <Availability2.h>

@interface UIDateLabel : UILabel {
	double _date;
	int _dateKey;
	BOOL _boldForAllLocales;
}
@property(assign, nonatomic) BOOL boldForAllLocales;
+(id)defaultFont;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(int)_dateKey;
-(void)_invalidateDateKey;
-(void)setFont:(id)font;
-(void)setFontWithoutInvalidation:(id)invalidation;
-(void)_updateDateStrings;
-(id)text;
-(id)font;
-(id)timeDesignator;
-(void)sizeToFit;
-(void)setDate:(id)date;
-(void)setTimeInterval:(double)interval;
-(double)timeInterval;
-(id)timeDesignatorFont;
-(void)drawTextInRect:(CGRect)rect;
-(void)drawRect:(CGRect)rect;
-(id)_dateLabelCache __OSX_AVAILABLE_STARTING(__MAC_NA, __IPHONE_3_1);
@end

