/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */



@protocol UIFormPeripheral
-(void)setPeripheralFormNode:(id)node;
-(void)beginEditing;
-(void)endEditing;
-(void)reset;
-(id)peripheralFormNode;
-(BOOL)isKeyboard;
@end

