/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "UIAnimation.h"


@interface UIGestureAnimation : UIAnimation {
	SEL _progressSelector;
	int _gestureType;
}
-(id)initWithTarget:(id)target progressSelector:(SEL)selector gestureType:(int)type;
-(void)setProgress:(float)progress;
-(int)gestureType;
@end

