/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <Foundation/NSObject.h>


@interface UIGroupInsertionItem : NSObject {
	int _index;
	NSRange _range;
}
-(id)initWithExistingGroup:(int)existingGroup andRowRange:(NSRange)range;
-(id)initWithNewGroupBeforeGroup:(int)newGroupBeforeGroup andRowCount:(int)count;
-(int)groupIndex;
-(NSRange)range;
@end

