/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIGroupTableViewCellBackground.h"
#import "UIKit-Structs.h"
#import <UIKit/UIView.h>


@interface UIGroupTableViewCellBackground : UIView {
	int _sectionLocation;
	int _animationCount;
	BOOL _disableSeparator;
	UIView* _separatorView;
}
@property(assign, nonatomic) int sectionLocation;
+(void)_flushCacheOnMemoryWarning:(id)warning;
+(void)initialize;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(void)_setSectionLocationAnimationDidStop;
-(void)setSectionLocation:(int)location animated:(BOOL)animated;
-(void)setBackgroundColor:(id)color;
-(id)backgroundColor;
-(void)layoutSubviews;
@end

@interface UIGroupTableViewCellBackground (UIGroupTableViewCellBackgroundInternal)
-(CGContextRef)_createContextForCachingWithFrame:(CGRect)frame isOpaque:(BOOL)opaque;
-(CGImageRef)_cachedImageWithSize:(CGSize)size forBackgroundColor:(id)backgroundColor borderColor:(id)color fillColor:(id)color4 leftPhase:(float)phase rightPhase:(float)phase6 ignoreSectionLocation:(BOOL)location;
-(CGRect)_contentRectForContentHeight:(float)contentHeight;
-(void)_incrementAnimationCount;
-(void)_decrementAnimationCount;
-(id)_backgroundColor;
-(id)_borderColor;
-(id)_fillColor;
-(void)_updateSeparatorView;
-(void)_updateContentsRectAndCenter;
-(void)_layoutSubviews:(BOOL)subviews;
@end

