/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIImage.h>
#import <Foundation/NSObject.h>


@interface UIImage ()
+(void)initialize;
-(void)dealloc;
-(void)drawAtPoint:(CGPoint)point;
-(void)drawInRect:(CGRect)rect;
-(void)drawAsPatternInRect:(CGRect)rect;
-(id)_automationID;
@end

@interface UIImage (ApplicationIconPrivate)
-(id)_applicationIconWithSize:(CGSize)size destinationFrame:(CGRect)frame shadowImage:(id)image overlayImage:(id)image4 outlineImage:(id)image5 maskImage:(id)image6;
-(id)_applicationIconImagePrecomposed:(BOOL)precomposed;
-(id)_smallApplicationIconImagePrecomposed:(BOOL)precomposed;
@end

@interface UIImage (UIImageInternal)
+(void)_flushSharedImageCache;
+(void)_flushCacheOnMemoryWarning:(id)warning;
-(void)_setCached:(BOOL)cached;
-(BOOL)_isCached;
-(void)_setNamed:(BOOL)named;
-(BOOL)_isNamed;
-(id)_flatImageWithWhite:(float)white alpha:(float)alpha;
-(id)_bezeledImageWithRed:(float)red green:(float)green blue:(float)blue alpha:(float)alpha;
-(id)_imageScaledToSize:(CGSize)size interpolationQuality:(CGInterpolationQuality)quality;
-(id)_imageScaledToProportion:(CGFloat)proportion interpolationQuality:(CGInterpolationQuality)quality;
@end

@interface UIImage (UIImageDeprecated)
+(id)imageNamed:(id)named inBundle:(id)bundle;
+(id)imageAtPath:(id)path;
+(void)removeImageNameFromCache:(id)cache;
-(id)initWithData:(id)data cache:(BOOL)cache;
-(id)initWithImageRef:(CGImageRef)imageRef;
-(CGImageRef)imageRef;
-(void)compositeToRect:(CGRect)rect fromRect:(CGRect)rect2 operation:(int)operation fraction:(float)fraction;
-(void)compositeToPoint:(CGPoint)point fromRect:(CGRect)rect operation:(int)operation fraction:(float)fraction;
-(void)compositeToPoint:(CGPoint)point operation:(int)operation fraction:(float)fraction;
-(void)compositeToPoint:(CGPoint)point operation:(int)operation;
-(void)draw9PartImageWithSliceRects:(XXStruct_4cr1oD)sliceRects inRect:(CGRect)rect;
-(void)draw9PartImageWithSliceRects:(XXStruct_4cr1oD)sliceRects inRect:(CGRect)rect fraction:(float)fraction;
-(void)draw9PartImageWithSliceRects:(XXStruct_4cr1oD)sliceRects inRect:(CGRect)rect operation:(int)operation fraction:(float)fraction;
-(void)draw3PartImageWithSliceRects:(XXStruct_UUz0SD)sliceRects inRect:(CGRect)rect;
-(void)draw3PartImageWithSliceRects:(XXStruct_UUz0SD)sliceRects inRect:(CGRect)rect fraction:(float)fraction;
-(void)draw3PartImageWithSliceRects:(XXStruct_UUz0SD)sliceRects inRect:(CGRect)rect operation:(int)operation fraction:(float)fraction;
-(void)draw1PartImageInRect:(CGRect)rect;
-(void)draw1PartImageInRect:(CGRect)rect fraction:(float)fraction;
-(void)draw1PartImageInRect:(CGRect)rect fraction:(float)fraction operation:(int)operation;
-(CGColorRef)_patternColor;
-(id)patternColor;
@end

@interface UIImage (UIImagePrivate)
+(UIImage*)applicationImageNamed:(NSString*)name;
+(UIImage*)kitImageNamed:(NSString*)name;
+(UIImage*)defaultDesktopImage;
+(void)setDesktopImageData:(id)data;
+(id)imageFromAlbumArtData:(id)albumArtData height:(int)height width:(int)width cache:(BOOL)cache;
-(id)initWithContentsOfFile:(id)file cache:(BOOL)cache;
-(id)initWithCGImage:(CGImageRef)cgimage imageOrientation:(int)orientation;
-(id)initWithIOSurface:(IOSurfaceRef)iosurface;
-(IOSurfaceRef)ioSurface;
@end

