/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UILabel.h>


@interface UIKeyboardCandidateInlineTextLabelView : UILabel {
}
+(id)font;
-(id)initWithFrame:(CGRect)frame;
-(int)textEffectsVisibilityLevel;
@end

