/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKeyboardLayoutProtocol.h"
#import "UIKit-Structs.h"
#import <UIKit/UIView.h>


@interface UIKeyboardLayout : UIView <UIKeyboardLayoutProtocol> {
	unsigned m_currentPathFlags;
	XXStruct__FxRIA m_activePathInfo;
	int m_shiftKeyPathIndex;
	int m_swipePathIndex;
}
-(id)initWithFrame:(CGRect)frame;
-(void)showKeyboardType:(int)type withAppearance:(int)appearance;
-(void)deactivateActiveKeys;
-(void)updateReturnKey;
-(void)updateLocalizedKeys;
-(BOOL)usesAutoShift;
-(void)setShift:(BOOL)shift;
-(BOOL)isShiftKeyBeingHeld;
-(BOOL)isShiftKeyPlaneChooser;
-(BOOL)shiftKeyRequiresImmediateUpdate;
-(void)longPressAction;
-(BOOL)canHandleHandEvent:(GSEventRef)event;
-(BOOL)handleHandEvent:(GSEventRef)event;
-(void)didClearInput;
-(id)candidateList;
-(void)setLabel:(id)label forKey:(id)key;
-(void)setTarget:(id)target forKey:(id)key;
-(void)setAction:(SEL)action forKey:(id)key;
-(void)setLongPressAction:(SEL)action forKey:(id)key;
-(void)restoreDefaultsForKey:(id)key;
-(void)restoreDefaultsForAllKeys;
-(id)activationIndicatorView;
-(BOOL)shouldShowIndicator;
-(void)handleHardwareKeyDownFromSimulator:(GSEventRef)simulator;
-(void)touchDown:(GSEventRef)down withPathInfo:(XXStruct__FxRIA*)pathInfo;
-(void)touchDragged:(GSEventRef)dragged withPathInfo:(XXStruct__FxRIA*)pathInfo;
-(void)touchUp:(GSEventRef)up withPathInfo:(XXStruct__FxRIA*)pathInfo;
-(BOOL)cancelTouchTracking;
-(BOOL)cancelMouseTracking;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)phraseBoundaryDidChange;
@end

