/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <UIKit/UILocalizedIndexedCollation.h>
#import <Foundation/NSObject.h>
#import <Availability.h>

@class NSArray, NSLocale;

@interface UILocalizedIndexedCollation ()
+(id)currentCollation;
-(void)dealloc;
-(int)sectionForSectionIndexTitleAtIndex:(int)index;
-(int)sectionForObject:(id)object collationStringSelector:(SEL)selector;
@end

@interface UILocalizedIndexedCollation (UIKitInternal)
+(id)collationWithDictionary:(id)dictionary;
-(id)initWithDictionary:(id)dictionary;
-(id)transformedCollationStringForString:(id)string __OSX_AVAILABLE_STARTING(__MAC_NA, __IPHONE_3_1);
@end

