/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIView.h>

@class UINavigationItem, UIFont;

@interface UINavigationItemView : UIView {
	UIFont* _font;
	UINavigationItem* _item;
	float _titleWidth;
	BOOL _titleAutosizesToFit;
}
-(id)initWithNavigationItem:(id)navigationItem;
-(id)navigationItem;
-(id)_defaultFont;
-(void)drawText:(id)text inRect:(CGRect)rect;
-(void)setFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
-(void)_resetTitleWidth;
-(float)_titleWidth;
-(id)title;
-(void)setTitleAutoresizesToFit:(BOOL)fit;
-(BOOL)titleAutoresizesToFit;
-(void)setFont:(id)font;
-(id)font;
-(id)_scriptingInfo;
@end

