/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIView.h>

@class UIColor;

@interface UINavigationBarBackground : UIView {
	int _barStyle;
	UIColor* _tintColor;
	struct {
		unsigned isTranslucent : 1;
	} _navbarFlags;
}
-(id)initWithFrame:(CGRect)frame withBarStyle:(int)barStyle withTintColor:(id)tintColor isTranslucent:(BOOL)translucent;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
@end

