/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "NSCoding.h"
#import <UIKit/UIView.h>
#import <Availability.h>

@interface UINavigationTransitionView : UIView <NSCoding> {
	id _delegate;
	UIView* _fromView;
	UIView* _toView;
	int _transition;
	UIView* _firstResponderToRestore;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_1
	float _fromViewAlpha;
#endif
	unsigned _isTransitioning : 1;
}
@property(assign, nonatomic) id delegate;
+(double)defaultDurationForTransition:(int)transition;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(BOOL)transition:(int)transition toView:(id)view;
-(BOOL)transition:(int)transition fromView:(id)view toView:(id)view3;
-(BOOL)isTransitioning;
-(void)_notifyDelegateTransitionDidStopWithContext:(id)_notifyDelegateTransition;
-(void)_navigationTransitionDidStop;
@end

