/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIView.h>

@class UIImage;

@interface UIOldSliderFillView : UIView {
	UIImage* _sliderImage;
}
-(id)initWithFrame:(CGRect)frame image:(id)image;
-(void)drawRect:(CGRect)rect;
@end

