/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "UIThreePartButton.h"


@interface UIPlacardButton : UIThreePartButton {
}
+(id)defaultFont;
-(id)initWithFrame:(CGRect)frame isShort:(BOOL)aShort;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithTitle:(id)title autosizesToFit:(BOOL)fit isShort:(BOOL)aShort;
@end

