/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface UIProxyObject : NSObject <NSCoding> {
	NSString* proxiedObjectIdentifier;
}
+(CFDictionaryRef)proxyDecodingMap;
+(void)addMappingFromIdentifier:(id)identifier toObject:(id)object forCoder:(id)coder;
+(void)addMappings:(id)mappings forCoder:(id)coder;
+(id)mappedObjectForCoder:(id)coder withIdentifier:(id)identifier;
+(void)removeMappingsForCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)setProxiedObjectIdentifier:(id)identifier;
-(id)proxiedObjectIdentifier;
@end

