/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <UIKit/UIResponder.h>
#import "UIKit-Structs.h"
#import <Foundation/NSObject.h>

@class NSUndoManager;

@interface UIResponder ()
-(void)mouseDown:(GSEventRef)down;
-(void)mouseUp:(GSEventRef)up;
-(void)mouseDragged:(GSEventRef)dragged;
-(void)mouseEntered:(GSEventRef)entered;
-(void)mouseExited:(GSEventRef)exited;
-(void)mouseMoved:(GSEventRef)moved;
-(void)scrollWheel:(GSEventRef)wheel;
-(void)keyDown:(GSEventRef)down;
-(void)keyUp:(GSEventRef)up;
-(void)gestureStarted:(GSEventRef)started;
-(void)gestureEnded:(GSEventRef)ended;
-(void)gestureChanged:(GSEventRef)changed;
-(BOOL)_containedInAbsoluteResponderChain;
-(BOOL)_containsResponder:(id)responder;
-(BOOL)becomeFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(BOOL)resignFirstResponder;
-(BOOL)canResignFirstResponder;
-(BOOL)isFirstResponder;
-(id)firstResponder;
-(void)_clearBecomeFirstResponderWhenCapable;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
@end

@interface UIResponder (Static)
-(void)_setFirstResponder:(id)responder;
-(id)_firstResponder;
-(id)_responderForBecomeFirstResponder;
-(BOOL)_becomeFirstResponderWhenPossible;
@end

@interface UIResponder (Internal)
-(void)_controlMouseDown:(GSEventRef)down;
-(void)_controlMouseUp:(GSEventRef)up;
-(void)_controlMouseDragged:(GSEventRef)dragged;
-(void)_controlTouchBegan:(id)began withEvent:(id)event;
-(void)_controlTouchMoved:(id)moved withEvent:(id)event;
-(void)_controlTouchEnded:(id)ended withEvent:(id)event;
-(id)_targetForAction:(SEL)action withSender:(id)sender;
@end

