/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "UIRemoveControlMinusButton.h"


@interface UIRemoveControlMultiSelectButton : UIRemoveControlMinusButton {
	unsigned _isHighlighted : 1;
	unsigned _isSelected : 1;
}
+(float)defaultWidth;
+(id)minusImage;
+(id)plusImage;
+(id)minusCenterImage;
-(id)initWithRemoveControl:(id)removeControl;
-(void)toggleRotate:(BOOL)rotate;
-(BOOL)isRotated;
-(BOOL)isRotating;
-(BOOL)isHiding;
-(void)setHiding:(BOOL)hiding;
-(void)drawRect:(CGRect)rect;
-(void)setSelected:(BOOL)selected highlighted:(BOOL)highlighted;
-(void)setHighlighted:(BOOL)highlighted;
-(BOOL)isHighlighted;
-(void)setSelected:(BOOL)selected;
@end

