/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "UIAnimation.h"


@interface UIScrollAnimation : UIAnimation {
	CGPoint _startPoint;
	CGPoint _endPoint;
}
-(void)setStartPoint:(CGPoint)point;
-(void)setEndPoint:(CGPoint)point;
-(void)setProgress:(float)progress;
@end

