/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "NSCoding.h"
#import <UIKit/UIScrollView.h>
#import <UIKit/UIView.h>
#import <Availability2.h>

@class NSArray, UIImageView;
@protocol UIScrollViewDelegate;

@interface UIScrollView ()
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(void)_populateArchivedSubviews:(id)subviews;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)_pinchGesture;
-(void)_updatePinchGesture;
-(id)_panGesture;
-(id)_scrollViewTouchDelayGesture;
-(void)setFrame:(CGRect)frame;
-(void)setBounds:(CGRect)bounds;
-(void)removeFromSuperview;
-(void)_didMoveFromWindow:(id)window toWindow:(id)window2;
-(void)setContentOffset:(CGPoint)offset animated:(BOOL)animated;
-(void)scrollRectToVisible:(CGRect)visible animated:(BOOL)animated;
-(void)setProgrammaticScrollEnabled:(BOOL)enabled;
-(BOOL)isProgrammaticScrollEnabled;
-(float)horizontalScrollDecelerationFactor;
-(void)setHorizontalScrollDecelerationFactor:(float)factor;
-(float)verticalScrollDecelerationFactor;
-(void)setVerticalScrollDecelerationFactor:(float)factor;
-(BOOL)usesGestureRecognizers;
-(void)delayed:(id)delayed;
-(void)setUsesGestureRecognizers:(BOOL)recognizers;
-(void)flashScrollIndicators;
-(void)_setShowsBackgroundShadow:(BOOL)shadow __OSX_AVAILABLE_STARTING(__MAC_NA, __IPHONE_3_1);
-(BOOL)_showsBackgroundShadow __OSX_AVAILABLE_STARTING(__MAC_NA, __IPHONE_3_1);
-(void)setShowBackgroundShadow:(BOOL)shadow;
-(BOOL)showBackgroundShadow __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_NA, __MAC_NA, __IPHONE_2_0, __IPHONE_3_1);
-(id)commonHitTest:(id)test;
-(id)hitTest:(CGPoint)test forEvent:(GSEventRef)event;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(BOOL)_usesDifferentHitTestForGestures;
-(id)_gestureTargetHitTest:(CGPoint)test withEvent:(id)event;
-(void)_scrollViewWillBeginDragging;
-(void)_scrollViewDidEndDecelerating;
-(CGPoint)_touchPositionForTouches:(id)touches;
-(BOOL)_updatePanWithStartDelta:(CGSize)startDelta event:(id)event gesture:(id)gesture ignoringDirectionalScroll:(BOOL)scroll;
-(void)_endPanWithEvent:(id)event;
-(id)_getDelegateZoomView;
-(void)handlePan:(id)pan;
-(void)handlePinch:(id)pinch;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)_touchesEnded:(id)ended withEvent:(id)event wasCancelled:(BOOL)cancelled;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(BOOL)canHandleSwipes;
-(int)swipe:(int)swipe withEvent:(GSEventRef)event;
-(BOOL)cancelTouchTracking;
-(BOOL)cancelMouseTracking;
-(void)cancelNextContentTouchEnded;
-(float)_zoomRubberBandScaleForScale:(float)scale;
-(void)setZoomScale:(CGFloat)scale animated:(BOOL)animated;
-(void)zoomToRect:(CGRect)rect animated:(BOOL)animated;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
-(void)_centerContentIfNecessary;
// -(void)layoutSubviews;
-(void)_updatePagingGesture;
-(void)setZoomEnabled:(BOOL)enabled;
-(BOOL)isZoomEnabled;
-(void)setAllowsMultipleFingers:(BOOL)fingers;
-(BOOL)allowsMultipleFingers;
-(void)willRotateToInterfaceOrientation:(id)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(id)interfaceOrientation;
-(void)_registerForRotation:(BOOL)rotation ofWindow:(id)window;
-(BOOL)preservesCenterDuringRotation;
-(void)setPreservesCenterDuringRotation:(BOOL)rotation;
-(void)_willMoveToWindow:(id)window;
-(CADoublePoint)_rubberBandContentOffsetForOffset:(CADoublePoint)offset outsideX:(BOOL*)x outsideY:(BOOL*)y;
-(void)_setZoomAnchorPoint:(CADoublePoint)point;
-(CADoublePoint)_zoomAnchorPoint;
-(void)_updatePinch:(id)pinch forState:(int)state;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(void)gestureRecognizerFailed:(id)failed;
-(void)_handleSwipe:(id)swipe;
-(void)_zoomToCenter:(CGPoint)center scale:(float)scale duration:(double)duration;
-(void)_zoomToCenter:(CGPoint)center scale:(float)scale duration:(double)duration force:(BOOL)force;
-(float)_zoomAnimationDurationForScale:(float)scale;
-(void)_zoomAnimationDidStop;
-(void)_adjustContentSizeForView:(id)view atScale:(float)scale;
-(void)setZoomScale:(float)scale withAnchorPoint:(CGPoint)anchorPoint validatingScrollOffset:(BOOL)offset allowRubberbanding:(BOOL)rubberbanding animated:(BOOL)animated duration:(double)duration notifyDelegate:(BOOL)delegate;
-(void)setZoomScale:(float)scale withAnchorPoint:(CGPoint)anchorPoint validatingScrollOffset:(BOOL)offset allowRubberbanding:(BOOL)rubberbanding animated:(BOOL)animated duration:(double)duration notifyDelegate:(BOOL)delegate force:(BOOL)force;
#else
-(void)_scrollViewDidEndDraggingWithDeceleration:(BOOL)_scrollView;
-(CGPoint)_centeredScrollPointForPoint:(CGPoint)point scale:(float)scale;
-(CGPoint)_zoomScrollPointForRect:(CGRect)rect scale:(float)scale;
-(void)setZoomScale:(float)scale withAnchorPoint:(CGPoint)anchorPoint validatingScrollOffset:(BOOL)offset allowRubberbanding:(BOOL)rubberbanding animated:(BOOL)animated;
#endif
@end

@interface UIScrollView (Static)
-(void)_notifyDidScroll;
-(void)_smoothScroll:(double)scroll;
-(BOOL)_continueScrollingAtOffset:(CGPoint)offset;
-(void)_popTrackingRunLoopMode;
-(void)_runLoopModePopped:(id)popped;
-(void)_startTimer:(BOOL)timer;
-(void)_deferredBeginTouchesInContentView;
-(void)_adjustScrollerIndicators:(BOOL)indicators alwaysShowingThem:(BOOL)them;
-(void)_adjustContentOffsetIfNecessary;
-(void)_hideScrollIndicators;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
-(BOOL)_getPagingDecelerationOffset:(CADoublePoint*)offset forTimeInterval:(double)timeInterval;
-(BOOL)_getBouncingDecelerationOffset:(CADoublePoint*)offset forTimeInterval:(double)timeInterval;
-(BOOL)_getStandardDecelerationOffset:(CADoublePoint*)offset forTimeInterval:(double)timeInterval;
-(void)_prepareToPageWithHorizontalVelocity:(float)horizontalVelocity verticalVelocity:(float)velocity;
#endif
@end

@interface UIScrollView (UIScrollViewInternal)
@property(assign, nonatomic, getter=isProgrammaticScrollEnabled) BOOL programmaticScrollEnabled;
-(void)_stopScrollDecelerationNotify:(BOOL)notify;
-(void)_stopScrollingNotify:(BOOL)notify dealloc:(BOOL)dealloc pin:(BOOL)pin;
-(void)_resetScrollingWithEvent:(GSEventRef)event;
-(void)_resetScrollingWithUIEvent:(id)uievent;
-(BOOL)_resetScrollingForGestureEvent:(id)gestureEvent;
-(void)_addScrollNotificationView:(id)view;
-(void)_removeScrollNotificationView:(id)view;
-(BOOL)_canCancelContentTouches:(id)touches;
-(BOOL)_cancelContentTouchWithEvent:(id)event forced:(BOOL)forced;
-(void)_addContentSubview:(id)subview atBack:(BOOL)back;
-(void)_moveContentSubview:(id)subview toBack:(BOOL)back;
-(void)_setContentOffsetAnimationDuration:(double)duration;
-(double)_contentOffsetAnimationDuration;
-(void)_setContentOffset:(CGPoint)offset animated:(BOOL)animated animationCurve:(int)curve;
-(void)_setAutomaticContentOffsetAdjustmentEnabled:(BOOL)enabled;
-(void)_scrollViewAnimationEnded;
-(BOOL)_scrollToTop;
-(BOOL)_scrollsToMakeFirstResponderVisible;
-(id)_defaultHitTest:(CGPoint)test withEvent:(id)event;
-(id)_hitTestForContentView:(CGPoint)contentView withEvent:(id)event;
-(void)_beginTouchesInContentView:(id)contentView touches:(id)touches withEvent:(id)event;
-(id)_touchedContentView;
-(double)_touchDelayForScrollDetection;
-(CGPoint)_stopOffset;
-(double)_horizontalVelocity;
-(double)_verticalVelocity;
-(void)_shiftOffset:(CGSize)offset;
-(void)_adjustForAutomaticKeyboardInfo:(id)automaticKeyboardInfo lastAdjustment:(float*)adjustment;
-(BOOL)_canScrollX;
-(BOOL)_canScrollY;
-(void)_setAutoscrolling:(BOOL)autoscrolling;
-(BOOL)_isAutoscrolling;
-(CGPoint)autoscrollContentOffset;
-(void)setAutoscrollContentOffset:(CGPoint)offset;
-(CGRect)contentFrameForView:(id)view;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
+(float)_cancelSelectDistance;
-(void)setBouncesHorizontally:(BOOL)horizontally;
-(BOOL)bouncesHorizontally;
-(void)setBouncesVertically:(BOOL)vertically;
-(BOOL)bouncesVertically;
-(float)_scrollHysteresis;
-(void)_scrollViewWillBeginZooming;
-(void)_scrollViewDidEndZooming;
-(float)_zoomScaleFromPresentationLayer:(BOOL)presentationLayer;
-(void)_adjustBackgroundShadowsForContentSizeForcedVisible:(BOOL)contentSizeForcedVisible;
-(BOOL)_beginTrackingWithEvent:(id)event;
-(void)_clearContentOffsetAnimation;
-(void)_forceDelegateScrollViewDidZoom:(BOOL)_forceDelegateScrollView;
-(void)_scrollViewDidEndDraggingWithDeceleration:(BOOL)_scrollView;
-(id)_parentScrollView;
-(void)_notifyPopOverIsScrolling:(BOOL)scrolling;
-(void)_notifyPopOverStoppedScrolling;
-(void)_notifyPopOverStoppedScrollingLater;
-(BOOL)_pagingLeft;
-(BOOL)_pagingRight;
-(void)_skipNextStartOffsetAdjustment;
-(BOOL)_isAnimatingContentOffset;
#else
-(void)_adjustBackgroundShadowsForContentSize;
-(void)_scrollGestureFailed;
#endif
@end

@interface UIScrollView (UIScrollViewGestures)
-(CGPoint)offset;
-(void)setOffset:(CGPoint)offset;
-(void)setScrollingEnabled:(BOOL)enabled;
-(void)_startGesture:(id)gesture withEvent:(id)event;
-(void)_changedGesture:(id)gesture withEvent:(id)event;
-(void)_endGesture:(id)gesture withEvent:(id)event;
-(void)didFinishGesture:(int)gesture inView:(id)view forEvent:(GSEventRef)event;
@end

@interface UIScrollView (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

@interface UIScrollView (UIAutoscrollAdditions)
-(BOOL)_isScrollingEnabled;
@end

@interface UIScrollView (UITextRangeViewScrollerSupport)
-(void)_enableScrollingIfNecessary;
-(void)_disableScrollingIfNecessary;
@end

#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
@interface UIScrollView (UIWebSelectionAutoscroll)
-(int)scrollableDirections;
-(float)maxVelocityInDirection:(int)direction;
@end
#endif

