/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UITextField.h>


@interface UISearchBarTextField : UITextField {
}
-(BOOL)_hasActionForEventMask:(int)eventMask;
-(CGRect)textRectForBounds:(CGRect)bounds;
-(CGRect)editingRectForBounds:(CGRect)bounds;
-(CGRect)leftViewRectForBounds:(CGRect)bounds;
-(CGRect)rightViewRectForBounds:(CGRect)bounds;
-(BOOL)_becomeFirstResponderWhenPossible;
@end

