/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIView.h>
#import <Availability2.h>

@class UIImage;

#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_1
__attribute__((visibility("hidden")))
#endif
@interface UISelectionIndicatorView : UIView {
	UIImage* _image;
	XXStruct_4cr1oD _slices;
}
-(id)initWithFrame:(CGRect)frame withImageName:(id)imageName;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
@end

