/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "UITextTapRecognizer.h"

@class UIView;
@protocol UITextSelectingContent;

@interface UISelectionTapRecognizer : UITextTapRecognizer {
	UIView<UITextSelectingContent>* _textView;
}
@property(assign) UIView<UITextSelectingContent>* textView;
-(BOOL)isCloseToSelection;
-(void)setState:(int)state;
@end

