/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UILabel.h>


@interface UITextFieldLabel : UILabel {
}
-(void)_defaultDrawTextInRect:(CGRect)rect;
-(void)drawTextInRect:(CGRect)rect;
@end

