/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIWindow.h>
#import <Availability2.h>
#import "UIAutoRotatingWindow.h"

@class NSMutableArray;

@interface UITextEffectsWindow : 
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
UIAutoRotatingWindow
#else
UIWindow 
#endif
{
	unsigned _activeEffectsCount;
#if __IPHONE_OS_VERSION_MAX_ALLOWED < __IPHONE_3_2
	int _interfaceOrientation;
#endif
	NSMutableArray* _touchableSubviews;
}
+(UITextEffectsWindow*)sharedTextEffectsWindow;
+(UITextEffectsWindow*)sharedTextEffectsWindowAboveStatusBar;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
-(id)_earlyReturnHitTest:(CGPoint)test withEvent:(id)event;
#else
// inherited: -(BOOL)acceptsGlobalPoint:(CGPoint)point;
-(void)updateForOrientation:(int)orientation;
-(void)matchDeviceOrientation;
#endif
// inherited: -(id)hitTest:(CGPoint)test withEvent:(id)event;
// inherited: -(id)initWithFrame:(CGRect)frame output:(int)output bitsPerComponent:(int)component;
// inherited: -(void)dealloc;
// inherited: -(void)_didRemoveSubview:(id)subview;
-(void)didAddSubview:(id)subview;
-(void)_subviewInteractivityChanged:(id)changed;
// -(void)bringSubviewToFront:(id)front;
// -(void)sendSubviewToBack:(id)back;
-(void)sortSubviews;
-(BOOL)_isTextEffectsWindow __OSX_AVAILABLE_STARTING(__MAC_NA, __IPHONE_3_1);
@end

