/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIView.h>

@class UIImage;

@interface UIThreePartImageView : UIView {
	XXStruct_UUz0SD _slices;
	UIImage* _image;
}
-(void)dealloc;
-(void)setImage:(id)image;
-(void)setSlices:(XXStruct_UUz0SD)slices;
-(void)drawRect:(CGRect)rect;
@end

