/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>


@interface UIWebFormABCompatibility : NSObject {
}
+(int)convertID:(id)id;
@end

