/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIView.h>


@interface UIWebSelectionOutline : UIView {
	UIView* _lineViews[4];
}
-(id)initWithFrame:(CGRect)frame;
-(void)setFrame:(CGRect)frame;
-(void)layoutSubviews;
-(void)dealloc;
@end

