/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

#import "TelephonyUI-Structs.h"
#import <UIKit/UIImageView.h>

@class UIAlphaAnimation, TPBottomLockBar;

@interface TPLockKnobView : UIImageView {
	TPBottomLockBar* _track;
	UIAlphaAnimation* _animation;
	float _centerDelta;
	BOOL _tracking;
}
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(void)setLockView:(id)view;
@end

